### ISSUE TITLE
NonText with blue tildes don't look good

### ISSUE THREAD

**Issue by oblitum** [sainnhe/gruvbox-material#1]
![WogBghl](https://user-images.githubusercontent.com/1269815/61730769-709f7c80-ad50-11e9-9326-87eb30d97b4c.png)

**Comment by sainnhe** [comment]
I can't reproduce this, NonText is linked to Comment in this color scheme.

But I've changed to another way to highlight it, you can update this color scheme and see if it has been fixed.

**Comment by oblitum** [comment]
Thx, it's OK now.
