### ISSUE TITLE
Transparency of sign column

### ISSUE THREAD

**Issue by Krasjet** [sainnhe/gruvbox-material#10]
When `g:gruvbox_material_transparent_background` is turned on, the background of the sign column is still not transparent.

![pic-selected-191016-2341-40](https://user-images.githubusercontent.com/5229241/66976878-8384cd00-f071-11e9-86e3-a35977b072ab.png)

Related highlight groups of ALE, coc.nvim, and gitgutter might also need to be tweaked.

**Comment by sainnhe** [comment]
Done. You can update this color scheme and get it a try.
