### ISSUE TITLE
Cannot override highlights if loading from packer

### ISSUE THREAD

**Issue by sigzegv** [sainnhe/gruvbox-material#100]
I love this theme but I'm used to override some highlight styles. 
Until now I was using `gruvbox-material` with `vim-plug` loader, which works perfectly, and I had not issues overriding highlights.

Now I'm migrating to full lua conf and I noticed I cannot override highlights anymore if I load `gruvbox-material` with `packer`.

- Operating system/version: Ubuntu 20.04
- Terminal emulator/version: Kitty
- `echo $TERM`: xterm-256colors
- `nvim --version`: 0.5.0

### Minimal vimrc that can reproduce this bug
```vim
require'packer'.startup({
    function(use)
        use 'wbthomason/packer.nvim'
        use 'sainnhe/gruvbox-material'
    end,
})
 
vim.o.termguicolors = true
vim.o.background = "dark"
 
vim.cmd([[
    colorscheme gruvbox-material
    hi Normal guifg=#FF0000
]]
```

### Steps to reproduce this bug using minimal vimrc
Just run nvim with this init.lua, the point is that at first load, colorscheme is loaded correctly, but the `hi Normal` is not applied. After that if I made a manual reload with `:so %` in nvim the highlight is applied and the normal text becomes red.

![gruvbox-bug](https://user-images.githubusercontent.com/6304596/130647146-73b97c7c-4825-4a07-af54-846208351ba8.gif)

### Actual behaviour
The Normal text has the fg color as specified in the colorscheme.

### Expected behaviour
The guifg of Normal text should be red.

**Comment by sainnhe** [comment]
It's recommended to use autocmd instead.

https://github.com/sainnhe/gruvbox-material/blob/04fc67660a87adc2edbbc0b4b39d379e45c3baf8/doc/gruvbox-material.txt#L616-L649
