### ISSUE TITLE
add support for intellij idea

### ISSUE THREAD

**Issue by mxm5** [sainnhe/gruvbox-material#104]
add support for intellij idea

**Comment by weigao-123** [comment]
Yes, please, really like it!

**Comment by RenFraser** [comment]
@sainnhe are you open to this and if so, do you have a preference for how it's added to the repo?

**Comment by sainnhe** [comment]
I don't use idea and I'm not interested in creating a theme for it.

> do you have a preference for how it's added to the repo?

This repo is for vim theme only, if a new theme for idea has been created, it should be placed in a new repository, and maybe the url can be added to the wiki page if the author would like to.

If anyone wants to create a theme for idea, the color reference can be found in https://github.com/sainnhe/gruvbox-material/blob/master/autoload/gruvbox_material.vim

**Comment by RenFraser** [comment]
Thanks @sainnhe. I've attempted to copy it for IntelliJ. I might experiment with a repo myself at some point and see how it goes.

**Comment by antoineco** [comment]
Closing because not directly related to the Vim color scheme. Contributions are always welcome! Feel free to add them to https://github.com/sainnhe/gruvbox-material/wiki/Related-Projects
