### ISSUE TITLE
Add screenshots to README 

### ISSUE THREAD

**Issue by gozes** [sainnhe/gruvbox-material#106]
### Operating system/version

n/a

### Terminal emulator/version

n/a

### $TERM environment variable

n/a

### Feature matrix

n/a

### Minimal vimrc that can reproduce this bug.

n/a

### Steps to reproduce this bug using minimal vimrc

n/a

### Expected behavior

n/a

### Actual behavior

I would be nice to have screenshots of the theme on the readme so one con see what it look like before installing it

**Comment by sainnhe** [comment]
It's already there.
