### ISSUE TITLE
Add support for nvim-cmp highlight groups

### ISSUE THREAD

**Issue by marcomayer** [sainnhe/gruvbox-material#108]
Would be great to have these, if I find some time I'll do a PR myself. Link to groups: https://github.com/hrsh7th/nvim-cmp#highlights

**Comment by sainnhe** [comment]
Done via https://github.com/sainnhe/gruvbox-material/commit/13dc03fd1effbc8dcdb4f9fab70e9aef6f399498, I'm not sure if this highlight is OK though. You can update this color scheme and get it a try.

**Comment by marcomayer** [comment]
Nice, I think the gray is a bit too hard to read while matching, I prefer:
`highlight! link CmpItemAbbr Fg`
also
`highlight! link CmpItemMenu Fg`
is missing.

Here's what it look like:
![Screenshot 2021-10-12 at 12 23 05](https://user-images.githubusercontent.com/10881376/136938904-5ee98bc6-d3a4-42fa-9d8b-3e6c4fa6661c.png)
:

**Comment by sainnhe** [comment]
Thanks, I've updated `CmpItemAbbr` and `CmpItemMenu` to use `Fg` following your advise.

And I referenced the completion menu of vscode and added bold to matching characters.
