### ISSUE TITLE
[feature request] leave TS highlight to their default value

### ISSUE THREAD

**Issue by antoinemadec** [sainnhe/gruvbox-material#112]
This plugin redefines the TS highlights in ```colors/gruvbox-material.vim``` when nvim-treesitter already links them to standard highlights (Identifier, Function etc):
https://github.com/nvim-treesitter/nvim-treesitter/blob/master/plugin/nvim-treesitter.vim

The default TS highlights are actually better IMO.
For instance, it differentiates functions and built-it functions etc.

Would it be possible to remove the redefinition of TS highlights ?

PS: thanks for the amazing colorscheme ❤️

**Comment by sainnhe** [comment]
> The default TS highlights are actually better IMO.

I don't think so. For example, the default highlights will link `TSFuncBuiltin` to `Special` which is yellow in this color scheme, but yellow is designed to highlight data type, class, etc.

Optimized tree-sitter highlights pay more attention to the semantics in highlighting.

---

> Would it be possible to remove the redefinition of TS highlights ?

Actually the tree-sitter hi groups are linked to other hi groups, for example the semantic highlighting groups in coc.nvim:

https://github.com/sainnhe/gruvbox-material/blob/fb27ccbd20cc1eda04e181f22c722977bdf9c934/colors/gruvbox-material.vim#L515-L561

So removing TS highlights will lead to a lot of code refactoring.

---

If you don't like current TS highlighting, it's always welcome to fork this repository and modify the code by yourself, simply deleting related code should work:

https://github.com/sainnhe/gruvbox-material/blob/fb27ccbd20cc1eda04e181f22c722977bdf9c934/colors/gruvbox-material.vim#L457-L512
