### ISSUE TITLE
port to neovim.lua

### ISSUE THREAD

**Issue by debendraoli** [sainnhe/gruvbox-material#114]
Addtional plugins supports to be considered:

1. vim-signify
2. vim-startify
3. lspsaga.nvim
4. telescope.nvim

ref: https://github.com/ellisonleao/gruvbox.nvim

**Comment by dzintars** [comment]
In the latest traditions of "lualize everything", I would consider the following as well:
Vim-startify = VimScript
https://github.com/glepnir/dashboard-nvim = Lua

And i would give my vote for https://github.com/kyazdani42/nvim-tree.lua

**Comment by sainnhe** [comment]
You should really check if these plugins are already supported in this color scheme.

**Comment by dzintars** [comment]
I took a peek into `doc/gruvbox-material.txt`, but didn't saw them listed.

**Comment by sainnhe** [comment]
nvim /path/to/gruvbox-material/colors/gruvbox-material.vim

Press `za` to toggle folding.

**Comment by sainnhe** [comment]
All plugins mentioned above have been optimized now, closed.
