### ISSUE TITLE
Dim (gray out, fade out) unused identifiers

### ISSUE THREAD

**Issue by FernandoBasso** [sainnhe/gruvbox-material#116]
Thanks a lot for this awesome theme!

Here's a screenshot in Vim, with original Gruvbox:

![image](https://user-images.githubusercontent.com/6560620/148200883-0cb73a47-ce92-4744-b855-f6f474a049c7.png)

Note how `TheType` is dimmed/grayed out. And here's a screenshot with Neovim 6.1, with TreeSitter and gruvbox-material:

![image](https://user-images.githubusercontent.com/6560620/148201667-5bc4f0c7-71f5-4873-8be5-da2f1052320c.png)

In both cases I'm using coc.vim with a TypeScript buffer.

I tried to look at the source code for gruvbox-material but couldn't find out if this feature is just not-implemented, or I am lacking some configuration. I see `highlight! link CocFadeOut Grey` in the `gruvbox-material.vim` file but not sure why it is not kicking in.

This is my current  gruvbox-material configuration:

```vim
set background=dark
let g:gruvbox_material_palette = 'material'
let g:gruvbox_material_disable_italic_comment = 1
let g:gruvbox_material_diagnostic_text_highlight = 0
let g:gruvbox_material_diagnostic_line_highlight = 0
let g:gruvbox_material_diagnostic_virtual_text = 'colored'
colorscheme gruvbox-material
```

This might be relevant: https://github.com/neoclide/coc.nvim/issues/1046.

**Comment by sainnhe** [comment]
I can't reproduce, please file a new issue and follow the issue template to provide detailed information.
