### ISSUE TITLE
How to set contrast?

### ISSUE THREAD

**Issue by m-kru** [sainnhe/gruvbox-material#12]
In README you show screenshots with different contrast, however I am not able to set them. I have tried `let g:gruvbox_material_contrast_dark="soft"`, but without success.

**Comment by rsaihe** [comment]
`let g:gruvbox_material_background = "soft"` should work, I believe.

**Comment by m-kru** [comment]
Works, thanks.

**Comment by rsaihe** [comment]
No problem! 👍

**Comment by rsaihe** [comment]
I feel like it could be mentioned more clearly in the README. Most of the other config options are fine to just have with `:help gruvbox-material-configuration` but I personally feel like the contrast options are used frequently enough that it might make sense to discuss them in the README itself too. What do you think? @sainnhe

**Comment by sainnhe** [comment]
Done! @rsaihe

**Comment by rsaihe** [comment]
Yay, that looks good! 😄
