### ISSUE TITLE
Diagnostic Colors are not functional

### ISSUE THREAD

**Issue by dathinaios** [sainnhe/gruvbox-material#127]
Thank you for the great theme! 🙂

As the title suggests the diagnostic colors are not displaying correctly. This is what I am getting:

![Screenshot 2022-04-27 at 23 46 50](https://user-images.githubusercontent.com/481589/165646838-df7d121c-640e-442b-8b2f-e39b30796de6.png)

Comparing to Nord:

![Screenshot 2022-04-27 at 23 46 11](https://user-images.githubusercontent.com/481589/165646875-e6df4bba-b7b5-47fa-a00f-62407cdbcf77.png)

I see there is a closed issue that suggests this is fixed so do let me know if this is just me..

**Comment by sainnhe** [comment]
Check these options:

https://github.com/sainnhe/gruvbox-material/blob/3d664943daf65bf99390a52c5dbc557f87fac552/doc/gruvbox-material.txt#L352-L413

**Comment by dathinaios** [comment]
Thank you! 🙏 I would suggest that it is more consistent that all syntax highlights are enabled by default and the options provided used for disabling.
