### ISSUE TITLE
[Feature request] Support for diagnostic_line_highlight using neovim's built-in language server client

### ISSUE THREAD

**Issue by raj-magesh** [sainnhe/gruvbox-material#129]
The diagnostic_line_highlight setting doesn't work for Neovim's builtin LSP yet. Could that please be implemented? Thank you!

**Comment by sainnhe** [comment]
This features should be implemented in a plugin. If this plugin provides some highlight groups that can customize the colors of diagnostic line, then this color scheme can optimize these highlight groups to use more suitable colors.

However I don't know of any plugins that support this feature.

**Comment by raj-magesh** [comment]
I see, I didn't realize that [trouble.nvim](https://github.com/folke/trouble.nvim) wasn't setting these highlight groups. Thanks!
