### ISSUE TITLE
Please support quick-scope

### ISSUE THREAD

**Issue by yutkat** [sainnhe/gruvbox-material#13]
The default settings are difficult for me to see

### sample

```
highlight QuickScopePrimary guifg='#afff5f' gui=underline ctermfg=155 cterm=underline
highlight QuickScopeSecondary guifg='#5fffff' gui=underline ctermfg=81 cterm=underline
```

https://github.com/unblevable/quick-scope

**Comment by sainnhe** [comment]
I created `quick-scope-1` and `quick-scope-2` branch with two different designs:

- `quick-scope-1`: Just like in the README of quick-scope, it uses existing foreground colors and underline.
- `quick-scope-2`: Do not change foreground colors, use [diff background colors](https://github.com/sainnhe/gruvbox-material/blob/master/templates/_palette_dark.colortemplate#L21-L29) and underline.

Which one do you think is better?

**Comment by yutkat** [comment]
Thank you for your quick reply :smile: 

I love quick-scope-1 because it's simpler than 2.
But I believe in your senses so leave it to you.

**Comment by sainnhe** [comment]
I finally decided to use `quick-scope-1`, let's believe in the author of this plugin.

**Comment by sainnhe** [comment]
Merged.

**Comment by yutkat** [comment]
Thank you!
