### ISSUE TITLE
No color for clojure keywords

### ISSUE THREAD

**Issue by ribelo** [sainnhe/gruvbox-material#132]
### Operating system/version

irrelevant

### Terminal emulator/version

irrelevant

### $TERM environment variable

irrelevant

### Tmux version

irrelevant

### Feature matrix

irrelevant

### Minimal vimrc that can reproduce this bug.

irrelevant

### Steps to reproduce this bug using minimal vimrc

open any clojure/script file

### Expected behavior

the color of the keywords should be different from the standard color

### Actual behavior

![2022-07-07-220245_grim](https://user-images.githubusercontent.com/1815898/177862052-43ec2eab-7fa5-4955-af78-64eccfdaff6d.png)

**Comment by ribelo** [comment]
The same problem is for everforest and edge.

**Comment by ribelo** [comment]
I found that for clojure keyword corresponds to `TSSymbol`

**Comment by sainnhe** [comment]
`TSSymbol` is a general highlight group that will effect all languages, so changing this hi groups will break the overall design of this color scheme.

If you don't care about other languages, you can modify this in your vimrc. See FAQ "How to use custom colors" in help doc.
