### ISSUE TITLE
Problem with Bufferline 2.6.0+

### ISSUE THREAD

**Issue by ribelo** [sainnhe/gruvbox-material#136]
Since bufferline has switched to `nvim_set_hl`, there has been a problem. Some of the colors are not used and I can't find the correlation. Definitely the colors associated with lsp diagnostic do not match. 

I don't know if this can be called an issue, but bufferline is pretty much the standard at least in the neovim world, and you could consider whether something should be done about it.

**Comment by sainnhe** [comment]
Could you provide minimal vimrc to reproduce this? I don't use bufferline so I'm not sure what's going on. It'll be better if you can provide a screenshot.

**Comment by sainnhe** [comment]
Closed due to unclear description.
