### ISSUE TITLE
[Feature Request] File Explorer Shading

### ISSUE THREAD

**Issue by AlexvZyl** [sainnhe/gruvbox-material#139]
Hi there, thanks for the awesome theme.

I would like to suggest an option for shading the window of the file explorer (or in this case, [nvim-tree.lua](https://github.com/kyazdani42/nvim-tree.lua)).  It would add a nice touch to the theme.  An example can be seen over at [nightfox.nvim](https://github.com/EdenEast/nightfox.nvim).

**Comment by AlexvZyl** [comment]
Here I am using [toggleterm.nvim](https://github.com/akinsho/toggleterm.nvim) which shades the terminal. 

![image](https://user-images.githubusercontent.com/81622310/188274668-05257b2f-6eb1-4237-b783-f383400f2308.png)

**Comment by antoineco** [comment]
Just so I understand correctly, by _shading_ you mean making the background of the file explorer darker than the default background, right?

**Comment by AlexvZyl** [comment]
Yes that is exactly what I mean.

**Comment by antoineco** [comment]
@Alex-vZyl I'm looking into this. So far I haven't found a way to do it without autocmds and window-local highlights (only supported in Neovim), but I may have overlooked something. I'll keep you posted.

**Comment by antoineco** [comment]
@Alex-vZyl OK, I found a much simpler way. It turns out nvim-tree provides all the highlighting groups needed to override its background color without relying on window-local highlights.

Could you please add this to your Neovim config and let me know what you think about the result?

<details>
<summary>
<h4>:page_facing_up: init.vim</h4>
</summary>

```vim
" Apply custom highlights on colorscheme change.
" Must be declared before executing ':colorscheme'.
augroup custom_highlights_gruvboxmaterial
  autocmd!
  " file explorer background
  autocmd ColorScheme gruvbox-material 
  \       hi NvimTreeNormal      guibg=#181818 |
  \       hi NvimTreeEndOfBuffer guibg=#181818
augroup END

colorscheme gruvbox-material
```

</details>

<details>
<summary>
<h4>:page_facing_up: init.lua</h4>
</summary>

```lua
-- Apply custom highlights on colorscheme change.
-- Must be declared before executing ':colorscheme'.
grpid = vim.api.nvim_create_augroup('custom_highlights_gruvboxmaterial', {})
vim.api.nvim_create_autocmd('ColorScheme', {
  group = grpid,
  pattern = 'gruvbox-material',
  command = -- file explorer background
            'hi NvimTreeNormal      guibg=#181818 |' ..
            'hi NvimTreeEndOfBuffer guibg=#181818'
})

vim.cmd'colorscheme gruvbox-material'
```

</details>

![image](https://user-images.githubusercontent.com/3299086/188838591-1d080f2d-5d9c-41dc-a403-4313c5419545.png)

Please bear in mind that `#181818` is not in the color scheme's palette, and is only presented as an example.

**Comment by sainnhe** [comment]
I'll add two new colors later, three plugins need to be optimized:

- nvim-tree
- bufferline
- barbar

**Comment by AlexvZyl** [comment]
@antoineco Here it is in my setup.

![image](https://user-images.githubusercontent.com/81622310/188868294-563ae6f0-4ed5-4e2d-8b0e-adfa819ed5fd.png)

It works well!  Definitely makes using file explorers inside neovim a lot nicer.  It is a slightly different shade than what bufferline and toggleterm uses, but it is not that big of a deal.  If you want you can support those plugins as well, but that is up to you.

**Comment by smartding** [comment]
Is there any way we can make this shading feature optional?
Not everyone likes it.
