### ISSUE TITLE
Please support vim-illuminate

### ISSUE THREAD

**Issue by yutkat** [sainnhe/gruvbox-material#14]
I'm sorry to send you another similar issue.

---

vim-illuminate has more than 400 stars and I think this plugin is famous. 
But It is hard to see the gruvbox-material's default settings.
I'd be happy to fix it.

### highlight group name

`hi illuminatedWord cterm=underline gui=underline`

https://github.com/RRethy/vim-illuminate

**Comment by sainnhe** [comment]
Thanks for your suggestion.

Currently vim-matchup is using underline and coc-highlight is using bold so I can distinguish between them.

What about using bold instead? This plugin looks very similar to coc-highlight functionally.

**Comment by yutkat** [comment]
Thank you. I decided to use coc-highlit :wink:

**Comment by yutkat** [comment]
My font did not include bold, so I changed it to include bold :smile:

**Comment by sainnhe** [comment]
I added a new option to control the behavior of coc-highlight and vim-illuminate, you can see `:h g:gruvbox_material_current_word` to get it a try.

**Comment by yutkat** [comment]
`let g:gruvbox_material_current_word = 'grey background'` is a great option for me!
Thank you very much :joy:

**Comment by sainnhe** [comment]
I finally decided to use `'grey background'` as default value, as some users may be using fonts that don't support bold, and more importantly, this is the default behavior of many other code editors such as vscode.
