### ISSUE TITLE
Wrong color of float win border

### ISSUE THREAD

**Issue by XXiaoA** [sainnhe/gruvbox-material#141]
### I have done the following steps before reporting this issue:

- [X] I have searched the existing issues
- [X] I have read the FAQ in the help doc

### Operating system/version

Ubuntu 22.04

### Terminal emulator/version

Wezterm

### $TERM environment variable

xterm-256color

### Feature matrix
```
NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -ffile-prefix-map=/build/neovim-Ch6Bi
n/neovim-0.8.0~ubuntu1+git202209052347-fb39bba5a-c99271b19=. -flto=au
to -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-s
trong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_S
OURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2
 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-pro
totypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing
-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-
fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-
color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGP
ACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/
neovim-Ch6Bin/neovim-0.8.0~ubuntu1+git202209052347-fb39bba5a-c99271b1
9/build/cmake.config -I/build/neovim-Ch6Bin/neovim-0.8.0~ubuntu1+git2
02209052347-fb39bba5a-c99271b19/src -I/build/neovim-Ch6Bin/neovim-0.8
.0~ubuntu1+git202209052347-fb39bba5a-c99271b19/.deps/usr/include -I/u
sr/include -I/build/neovim-Ch6Bin/neovim-0.8.0~ubuntu1+git20220905234
7-fb39bba5a-c99271b19/build/src/nvim/auto -I/build/neovim-Ch6Bin/neov
im-0.8.0~ubuntu1+git202209052347-fb39bba5a-c99271b19/build/include
Compiled by buildd@lcy02-amd64-037

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
### Minimal vimrc that can reproduce this bug.

use gruvbox_material without other configuration

### Steps to reproduce this bug using minimal vimrc

run `:lua vim.ui.input({}, function() end)` in neovim

### Expected behavior

a float win wich a normal border

![Screenshot_20220906_135514](https://user-images.githubusercontent.com/62557596/188557508-38cc05dc-1f3f-4080-b9a2-c62d4c188a57.png)

### Actual behavior

![Screenshot_20220906_135444](https://user-images.githubusercontent.com/62557596/188557518-7513255f-d8a3-4e91-9356-5a9d7ea290ba.png)
something wrong of border. the color around border should be same  as background

**Comment by antoineco** [comment]
@XXiaoA what plugin is that? On the latest Neovim nightly (v0.8.0-dev-1029-g05893aea3), `:lua vim.ui.input({}, function() end)` doesn't open such popup. The input is in the command line bar, at the bottom:

![image](https://user-images.githubusercontent.com/3299086/188596998-4e4c3b21-092c-4102-a063-96b4761fb431.png)
![image](https://user-images.githubusercontent.com/3299086/188597122-e82eb9ae-b341-48ed-a270-d663eb695a60.png)

**Comment by XXiaoA** [comment]
Sorry, I forgot I installed [dressing.nvim](https://github.com/stevearc/dressing.nvim). But it used the standard highlight groups for neovim floating windows. See [here](https://github.com/stevearc/dressing.nvim#highlights).

**Comment by antoineco** [comment]
OK thanks for double checking 👍 

Maybe @sainnhe can confirm, but to me it seems like a conscious design decision for this theme:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/3299086/188610306-1005fa6e-12b2-467d-8f3a-1f1c4d8e0da3.png">

Removing specific background styling makes the popup blend in, but as a result it also doesn't stand out from the main window:

<img width="516" alt="image" src="https://user-images.githubusercontent.com/3299086/188610757-c132ed60-120f-486a-a212-d63c4796597e.png">

The image (purple theme) you shared earlier does set the border background to the same color as the default background, but not in the center, so the result looks glitchy:

![image](https://user-images.githubusercontent.com/3299086/188611633-ee699e7c-6f66-41c8-977b-022f37ec0d9e.png)

Adopting this style in Gruvbox Material looks equally glitchy in my opinion:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/3299086/188611070-f71b13ca-4b9a-4540-b656-0960b281b0d1.png">

Out of these 3 variants, I personally find the current style the most readable while working with floating popups.

---

For the time being, my suggestion would be to apply local customisations using `autocmd` to tailor the look and feel of floating popups to your needs:

<details>
<summary>
<h4>:page_facing_up: .vimrc (Vim)</h4>
</summary>

```vim
" Apply custom highlights on colorscheme change.
" Must be declared before executing ':colorscheme'.
augroup custom_highlights_gruvboxmaterial
  autocmd!
  " floating popups
  autocmd ColorScheme gruvbox-material 
  \       hi NormalFloat guibg=#282828 |
  \       hi FloatBorder guibg=#282828
augroup END

colorscheme gruvbox-material
```

</details>

<details>
<summary>
<h4>:page_facing_up: init.lua (Neovim)</h4>
</summary>

```lua
-- Apply custom highlights on colorscheme change.
-- Must be declared before executing ':colorscheme'.
grpid = vim.api.nvim_create_augroup('custom_highlights_gruvboxmaterial', {})
vim.api.nvim_create_autocmd('ColorScheme', {
  group = grpid,
  pattern = 'gruvbox-material',
  command = -- floating popups
            'hi NormalFloat guibg=#282828 |' ..
            'hi FloatBorder guibg=#282828'
})

vim.cmd'colorscheme gruvbox-material'
```

</details>

**Comment by XXiaoA** [comment]
Okay, it does maybe a design for this colorscheme. I'll try use autocmd to configure it.

**Comment by mohammadlashkari** [comment]
Hi, the autocmd works perfectly, thanks. I just want to report that for the autocompletion panel with borders, it has the same behavior. Also, in the Harpoon pop-up panel, if you go to visual mode, you can't see the text selection area; the colors are the same.

![1](https://github.com/sainnhe/gruvbox-material/assets/112802776/5d81227f-2c17-4082-99dc-fc62ce770007)
![2](https://github.com/sainnhe/gruvbox-material/assets/112802776/5ad29ee2-3f23-41a9-8270-6668ffdf317f)
