### ISSUE TITLE
Background color not visible under transparent background

### ISSUE THREAD

**Issue by Krasjet** [sainnhe/gruvbox-material#15]
Since commit [09c87d4](https://github.com/sainnhe/gruvbox-material/commit/09c87d4ceb93a8557a42a0c7af650805d7a1de5b), the background color for search highlight, visual selections, current word highlight etc. become invisible under transparent mode.

I would suggest adding an option to use light background or reversed mode (in transparent mode).

Compare:
### Search [dark]
![pic-selected-191123-0533-10](https://user-images.githubusercontent.com/5229241/69477315-c6de0400-0db2-11ea-9931-7f2e53abd075.png)

### Search [reversed]
![pic-selected-191123-0534-58](https://user-images.githubusercontent.com/5229241/69477338-0a387280-0db3-11ea-8b6d-8a2ffc4e1fe3.png)

The dark background is barely visible.

**Comment by sainnhe** [comment]
There are some logic problems in the code, should be fixed via [5cabc09](https://github.com/sainnhe/gruvbox-material/commit/5cabc097e65817be56606921d06d930a91d4e932).

**Comment by sainnhe** [comment]
I've made more adjustments.

When in transparent mode, `Search` and `IncSearch` uses `reverse`  and `Current Word` uses bold by default.

**Comment by Krasjet** [comment]
I just noticed that `cursorline` is also not visible in transparent mode. I'm not using it but it could be considered a bug.

**Comment by sainnhe** [comment]
Should be fixed via [d3ac337](https://github.com/sainnhe/gruvbox-material/commit/d3ac337f79e83fec747220f660d4fa639401dea2).
