### ISSUE TITLE
Firefox theme

### ISSUE THREAD

**Issue by pietryszak** [sainnhe/gruvbox-material#150]
One of colors is not gruvbox material palete in firefox theme.
This blue color destroy a this nice theme.

![image](https://user-images.githubusercontent.com/45850093/197770329-47321a96-8785-42b3-871c-e34a3a3c1e92.png)

**Comment by antoineco** [comment]
Closing because there are multiple Gruvbox Material themes on the Firefox market and they are neither official nor related to Vim.
