### ISSUE TITLE
colorscheme variables undeclared

### ISSUE THREAD

**Issue by boredcoder411** [sainnhe/gruvbox-material#153]
once gruvbox-material is installed, and i try to run :colorscheme gruvbox-material, vim spits out a lot of errors about undeclared variables (image for reference) 
![Screenshot (93)](https://user-images.githubusercontent.com/105937655/200919992-fb13a7ea-4638-43ad-96e6-43ce18c1617a.png)

**Comment by antoineco** [comment]
@boredcoder411 your colorscheme isn't installed correctly. You copied the `colors` directory only. You also need the `autoload` directory.

All of this is [explained in the docs](https://github.com/sainnhe/gruvbox-material/blob/2807579bd0a9981575dbb518aa65d3206f04ea02/doc/gruvbox-material.txt#L83-L91).

**Comment by sainnhe** [comment]
Did you install this theme via pack feature? See FAQ, there's a workaround.
