### ISSUE TITLE
Dismiss warning message for better performance option

### ISSUE THREAD

**Issue by linrongbin16** [sainnhe/gruvbox-material#157]
I have tried better performance option. It will generate after syntax file for lazy loading.

But it will give warning message when generate this file. How to dismiss the message?

Can you add an option for it?

**Comment by sainnhe** [comment]
Why you want to dismiss it? It's expected behavior.

**Comment by linrongbin16** [comment]
> Why you want to dismiss it? It's expected behavior.

It's noisy to me. I don't want to see it.

**Comment by sainnhe** [comment]
This reason is not sufficient, I'm not going to implement all the features requests of users, only reasonable feature requests will be implemented.

You can fork this repository and remove related code.

**Comment by linrongbin16** [comment]
Hi @sainnhe , maybe my previous reason seems personal. But let users open vim and focus on working is definitely best user experience. I think it's worth.

**Comment by sainnhe** [comment]
This message will only popup after updating this color scheme, many plugins will also do similar things to notify users that it is updating or it's already been updated (e.g. nvim-treesitter).

If you don't want to see this message, you can simply don't update it.

**Comment by linrongbin16** [comment]
Got it thanks
