### ISSUE TITLE
Neotree background color

### ISSUE THREAD

**Issue by f73** [sainnhe/gruvbox-material#158]
Using gruvbox-material in AstroNvim. It seems since   `call gruvbox_material#highlight('NeoTreeNormal', s:palette.fg0, s:palette.bg_dim)` was introduced, background color of Neo-tree is a bit too dark. Is that by design? Background is even darker than in screenshot... Thanks!

![Screenshot from 2022-11-26 13-30-14](https://user-images.githubusercontent.com/16547841/204089151-2d733c1f-f009-47f6-9bef-21a165fab894.png)

**Comment by sainnhe** [comment]
Yes. Maybe I should add an option to control this behavior.

https://github.com/sainnhe/gruvbox-material/issues/139
