### ISSUE TITLE
[Feature] Color indicator for modified files

### ISSUE THREAD

**Issue by Krasjet** [sainnhe/gruvbox-material#16]
In [gruvbox-community](https://github.com/gruvbox-community/gruvbox), the vim-airline theme has a nice [color indicator](https://github.com/gruvbox-community/gruvbox/blob/master/autoload/airline/themes/gruvbox.vim#L22) for the filename of modified buffer

![pic-selected-191123-1449-32](https://user-images.githubusercontent.com/5229241/69484395-c704f080-0e00-11ea-8437-c2a99d3f561f.png)

compare with the current airline theme in gruvbox-material

![pic-selected-191123-1451-24](https://user-images.githubusercontent.com/5229241/69484419-06334180-0e01-11ea-87fc-2c154186d63f.png)

I found this feature quite useful even though I have a separate indicator for this. Is it possible to add a similar feature to gruvbox-material?

**Comment by sainnhe** [comment]
This is very easy. Which color do you prefer when the file has been modified?

**Comment by Krasjet** [comment]
`Blue` is probably more familiar to me as I was using "gruvbox-community", but I don't have a strong preference on this.

**Comment by sainnhe** [comment]
Done via [cd8d8a4](https://github.com/sainnhe/gruvbox-material/commit/cd8d8a4eadce5f7478854895b68a7945d3f0d8fa).

**Comment by sainnhe** [comment]
I just got a new idea. The color of modified file name can be changed in different mode, so I created a branch named `test_airline` based on this feature. Could you checkout this branch and get it a try?

**Comment by Krasjet** [comment]
Thank you for the hard work, though I can't say I like the idea of having different color in different modes. I think the goal of the highlight is to help me easily recognize if a file have been modified or not, not adding more color to the status line.

I'm quite satisfied with the result of using a single color for this because it's probably easier to associate `file modified` with `blue` rather than with `different colors in different modes` (BTW, there is no color highlighting in normal mode in the new branch).

**Comment by sainnhe** [comment]
You are right, there is no need for unnecessary beautification. After all, the goal of this color scheme is not to look good, but to protect the eyes of programmers and focus focus their attention on the code.

I'm going to delete this branch and continue to use the code in the master branch.
