### ISSUE TITLE
[question] How to install on LunarVim?

### ISSUE THREAD

**Issue by nandgator** [sainnhe/gruvbox-material#163]
How do I install this theme with [`Packer`](https://github.com/wbthomason/packer.nvim) in LuaVim?

**Comment by antoineco** [comment]
@joe733 the procedure is described [in LunarVim's docs](https://www.lunarvim.org/docs/plugins#user-plugins):

> User plugins can be installed by adding entries to the `lvim.plugins` table in your `config.lua` file, and saving or manually invoking `LvimReload` will trigger Packer to sync all the plugins in that table.
>
> ```lua
> lvim.plugins = {
>  {"lunarvim/colorschemes"},
>  {"folke/tokyonight.nvim"},
> }
> ```

For Gruvbox Material, simply add `sainnhe/gruvbox-material` to that list.

**Comment by nandgator** [comment]
Oh, it worked. Thank you!
