### ISSUE TITLE
[FEAT] diagnostic virtual text highlight support

### ISSUE THREAD

**Issue by baggiponte** [sainnhe/gruvbox-material#167]
Users can already set `gruvbox_material_diagnostic_line_highlight`  and `gruvbox_material_diagnostic_text_highlight`. How about adding a `gruvbox_material_diagnostic_virtual_text_highlight` to enable highlighted virtual text? Aside from my personal preference, I see it is quite common in other themes.

**Comment by sainnhe** [comment]
What do you mean by "highlighted virtual text"? Isn't it already been highlighted?

**Comment by baggiponte** [comment]
Thanks for the reply! When I toggle `gruvbox_material_diagnostic_virtual_text` I get virtual text in the same color as the warning. `gruvbox_material_diagnostic_text_highlight` highlights the diagnosed line. The feature I am describing should look like this:

![image](https://user-images.githubusercontent.com/57922983/222384783-dcbe7183-25a3-44d4-9bdb-aeb43b415d25.png)

Maybe there's something that overrides the highlight groups, I guess? For example, toggling `gruvbox_material_diagnostic_line_highlight` does not change anything for me.

**Comment by sainnhe** [comment]
I'm going to support this when I have time. Also, PR is welcome :)

**Comment by baggiponte** [comment]
Would love to! I have tried navigating the codebase but I am not too well-versed in vimscript. I guess I could help with the lua part! 💪🏼

**Comment by sainnhe** [comment]
Thanks! But this color scheme is mostly written in Vim Script. You can try to read the code if you are interested in it.

**Comment by antoineco** [comment]
@baggiponte I might be able to tackle that this weekend.

Just to make sure I understand exactly what you want, could you please share a screenshot of the _current_ behavior in Gruvbox Material.
So far you only shared a screenshot of a different colorscheme.

I don't colorize virtual text, and only use the default undercurl style myself, so I may not be aware of all the theming possibilities.

Thank you.

**Comment by antoineco** [comment]
@baggiponte I experimented with this a little bit, and here is the result (before/after):

![image](https://user-images.githubusercontent.com/3299086/233805313-4a26355d-620e-4298-b3c6-5ad666ccfd38.png)
![image](https://user-images.githubusercontent.com/3299086/233806735-9113dc7a-0d62-4398-964e-592173622196.png)

Is that the result you expect?

**Comment by baggiponte** [comment]
Hi @antoineco, sorry for the late reply. Thanks for working this out - this is what I had in mind!
