### ISSUE TITLE
How can I change tree background?

### ISSUE THREAD

**Issue by karambaq** [sainnhe/gruvbox-material#169]
### I have done the following steps before reporting this issue:

- [X] I have searched the existing issues
- [X] I have read the FAQ in the help doc

### Operating system/version

macOS

### Terminal emulator/version

iTerm

### $TERM environment variable

xterm-256color

### Tmux version

none

### Feature matrix

NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Скомпилирован  brew@Ventura

Features: +acl +iconv +tui
See ":help feature-compile"

            общесистемный файл vimrc: "$VIM/sysinit.vim"
          значение $VIM по умолчанию: "
/usr/local/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info

### Minimal vimrc that can reproduce this bug.

return {
  {
    "sainnhe/gruvbox-material",
    lazy = false, -- make sure we load this during startup if it is your main colorscheme
    priority = 1000,
  },
}

### Steps to reproduce this bug using minimal vimrc

return {
  {
    "sainnhe/gruvbox-material",
    lazy = false, -- make sure we load this during startup if it is your main colorscheme
    priority = 1000,
  },
}

### Expected behavior

```
vim.g.gruvbox_material_background = "medium" -- hard, soft, medium
vim.g.gruvbox_material_palette = "material" -- original, mix, material
vim.g.gruvbox_material_enable_italic = 1
vim.g.gruvbox_material_sign_column_background = 'none'

grpid = vim.api.nvim_create_augroup('custom_highlights_gruvboxmaterial', {})
vim.api.nvim_create_autocmd('ColorScheme', {
  group = grpid,
  pattern = 'gruvbox-material',
  command =
  'hi NvimTreeNormal                     guibg=#282828 |' ..
  'hi NvimTreeEndOfBuffer                guibg=#282828 |' ..
  'hi NoiceCmdlinePopupBorderCmdline     guifg=#ea6962 guibg=#282828 |' ..
  'hi TelescopePromptBorder              guifg=#ea6962 guibg=#282828 |' ..
  'hi TelescopePromptNormal              guifg=#ea6962 guibg=#282828 |' ..
  'hi TelescopePromptTitle               guifg=#ea6962 guibg=#282828 |' ..
  'hi TelescopePromptPrefix              guifg=#ea6962 guibg=#282828 |' ..
  'hi TelescopePromptCounter             guifg=#ea6962 guibg=#282828 |' ..
  'hi TelescopePreviewTitle              guifg=#89b482 guibg=#282828 |' ..
  'hi TelescopePreviewBorder             guifg=#89b482 guibg=#282828 |' ..
  'hi TelescopeResultsTitle              guifg=#89b482 guibg=#282828 |' ..
  'hi TelescopeResultsBorder             guifg=#89b482 guibg=#282828 |' ..
  'hi TelescopeMatching                  guifg=#d8a657 guibg=#282828 |' ..
  'hi TelescopeSelection                 guifg=#ffffff guibg=#32302f |' ..
  'hi FloatBorder                        guifg=#ea6962 guibg=#282828 |' ..
  'hi BqfPreviewBorder                   guifg=#ea6962 guibg=#282828 |' ..
  'hi NormalFloat                        guibg=#282828 |' ..
  'hi IndentBlanklineContextChar         guifg=#d3869b |' ..
  'hi markid1                            guifg=#ff8f88 |' ..
  'hi markid2                            guifg=#ffb074 |' ..
  'hi markid3                            guifg=#cfdc8b |' ..
  'hi markid4                            guifg=#a3d4c9 |' ..
  'hi markid5                            guifg=#f9acc1 |' ..
  'hi markid6                            guifg=#afdaa8 |' ..
  'hi markid7                            guifg=#fecc7d |' ..
  'hi markid8                            guifg=#eed8b2 |' ..
  'hi markid9                            guifg=#ffedc7 |' ..
  'hi markid10                           guifg=#cebfaa |' ..
  'hi StatusColumnBorder                 guifg=#232323 |' ..
  'hi StatusColumnBuffer                 guibg=#282828 |' ..
  'hi CursorLineNr                       guifg=#d8a657 |' ..
  'hi CodewindowBorder                   guifg=#ea6962 |'
})
vim.cmd'colorscheme gruvbox-material'

```

I've overrided NvimTreeNormal but it still the same color

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/14233969/225624456-bdbdd945-be8b-4818-b52e-663c4f95e8b2.png">

### Actual behavior

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/14233969/225624448-46c1dca8-f473-41e4-89e0-107b214c05d3.png">

**Comment by EricDriussi** [comment]
I'm having this issue as well, noticed after updating this plugin (was on `421ccc28df2b5c8aef06b40160d539684fd1e771` before).

Possibly related: I'm noticing a similar issue with the cmp popup, it doesn't seem to apply the same bg color as before.

**Comment by antoineco** [comment]
I used your exact code in my `init.lua` with Neovim 0.9, and the background of my Nvim-tree changed to `#282828`.

**Comment by antoineco** [comment]
Closing, feel free to reopen if you're still facing this issue.
