### ISSUE TITLE
Add specific configuration for Dart

### ISSUE THREAD

**Issue by smolck** [sainnhe/gruvbox-material#17]
There is already specific support in this colorscheme for Clojure, Rust, Lua, etc. However, there isn't any specific configuration for Dart, and I think the look when using [this dart syntax plugin in vim-polyglot](https://github.com/sheerun/vim-polyglot/blob/master/syntax/dart.vim) could be improved with some slight tweaks. Currently, it looks like this:

![image](https://user-images.githubusercontent.com/46855713/69595429-1e53be00-0fc5-11ea-8844-391720498948.png)

IMO there is too much yellow, especially when compared to Rust, which I think is more balanced:

![image](https://user-images.githubusercontent.com/46855713/69595388-01b78600-0fc5-11ea-9f0c-060842a84e9b.png)

Of course, this is just my opinion, and some people might think this looks fine. However, I wanted to bring this to light so that it might be improved if possible. Thanks!

**Comment by sainnhe** [comment]
I'm not familiar with dart, so could you try to optimize dart by yourself?

Here is a simple guide about how to optimize file types and hack this color scheme: [hack-color-schemes.md](https://gist.github.com/sainnhe/911f78cbb092ac58c8734c423a464935)

**Comment by smolck** [comment]
Sure! I’ll see what I can come up with and post it here, then make a PR for it if you like it. Sound good?

**Comment by smolck** [comment]
What do you think of this? I'm not so sure on my opinion of it, but maybe it's an improvement?

![image](https://user-images.githubusercontent.com/46855713/69597775-bef9ac00-0fcc-11ea-8740-099e11566604.png)

Note that the `Aqua` parts of the above screenshot are classes in Dart, while the `Yellow` parts are base types. If you think they should be colored differently, please let me know.

**Comment by sainnhe** [comment]
You don't need to get my approval. If you think this can be accepted by most of other dart programmers, then I'm going to merge it.

Btw, I personally think it looks good :)
