### ISSUE TITLE
Orange Indentline highlight in coc-explorer

### ISSUE THREAD

**Issue by leoatchina** [sainnhe/gruvbox-material#172]
### I have done the following steps before reporting this issue:

- [X] I have searched the existing issues
- [X] I have read the FAQ in the help doc

### Operating system/version

windows but ssh to linux 

### Terminal emulator/version

All terminal I have used , include  tabby , windows terminal, wezterm , mobaxterm

### $TERM environment variable

not need 

### Tmux version

not need 

### Feature matrix

Open  Coc-explore in vim/neovim,  either sidebar or float

### Minimal vimrc that can reproduce this bug.

not need ,  It happend when use colorscheme  `sonokai`, `edge`, `gruvbox-material`, `everest`

![image](https://user-images.githubusercontent.com/4470821/233242487-b7e3a5ba-2c3e-438c-99e3-e405febe8679.png)

After I changed colorscheme to `nightfox`
![image](https://user-images.githubusercontent.com/4470821/233242914-5f2ee622-3d85-46eb-ac42-72c4ddcf8248.png)

### Steps to reproduce this bug using minimal vimrc
0. install `coc.nvim`,  and `coc-explore`,  and opend `coc-explorer`
1. In nvim 0.9, I do `:inspect ` on the orange block
2.  got this
![image](https://user-images.githubusercontent.com/4470821/233242659-b9703fd0-b653-4d16-8c86-69f76ef71236.png)
3. do `verbose highlight CocExploreIndent`
4  got this
![image](https://user-images.githubusercontent.com/4470821/233242853-7311c46e-f62e-4c05-9fed-ab6339cd51ab.png)

### Expected behavior

not orange indentline

### Actual behavior

orange indentline

**Comment by antoineco** [comment]
Thanks for the very detailed issue report! 🙌 
Let me look into this.

**Comment by antoineco** [comment]
What does `:verbose hi Conceal` return?

**Comment by leoatchina** [comment]
```
Conceal        xxx ctermfg=239 ctermbg=202 guifg=#5a524c guibg=#ff5f00                                                                                                                                                                                                      
        最近修改于 ~/.leovim.d/plug/coc.nvim/indentLine/after/plugin/indentLine.vim line 88       
```

**Comment by antoineco** [comment]
There you go, `Conceal` was overwritten by indentLine.vim (`#5a524c` `#ff5f00`)

**Comment by antoineco** [comment]
Are you using a theme in your terminal which might be overriding grey colors, such as [base16-shell](https://github.com/chriskempson/base16-shell)?

**Comment by leoatchina** [comment]
Actually , after I deleted line 1493 in gruvbox-mateial.vim,  this bug disappeared
I donot installed `base16-shell`,  but have tested lots of colorschemes,  and I am sure this bug is only related with `edge`, `sonokai`, `gruvbox-material`, `everest`
![image](https://user-images.githubusercontent.com/4470821/233269479-635653c3-6720-4765-9247-8a8a11049032.png)

**Comment by antoineco** [comment]
indentline is forcing the background color to your terminal's color, so if you rewrote these to orange (like base16-shell does), they will show as orange in Vim too:

https://github.com/Yggdroot/indentLine/blob/d15d63bf9c4a74a02470d4bc8ecce53df13e3a75/after/plugin/indentLine.vim#L47-L53

What happens if you reload the colorscheme, for example with `:colorscheme desert | colorscheme gruvbox-material`?

**Comment by leoatchina** [comment]
>


sublime
![image](https://user-images.githubusercontent.com/4470821/233270576-31785407-7f12-4b1f-bb0c-3c1439ec9b4d.png)


 
desert
![image](https://user-images.githubusercontent.com/4470821/233270056-f88839c9-11a6-434c-8cae-f39350dc60d6.png)

edge
![image](https://user-images.githubusercontent.com/4470821/233270134-56d4fa52-9838-43dd-920b-2fa7a716ec19.png)

everforest
![image](https://user-images.githubusercontent.com/4470821/233270207-0b566e31-f9fe-4252-8bab-774d603f2b56.png)

sonokai
![image](https://user-images.githubusercontent.com/4470821/233270310-953deeb4-cf5a-4809-a3cc-195be58aae5c.png)


gruvbox-material after I delete line 1493
![image](https://user-images.githubusercontent.com/4470821/233270398-63c0769e-0173-45fd-8f86-5f919ac172ed.png)

**Comment by antoineco** [comment]
The reason why you don't see it in other colorschemes is because gruvbox-material (and all sainnhe's themes) doesn't force a background color, so indentline happily enforces its own color on top. This is a bad default from the plugin in my opinion.

https://github.com/sainnhe/gruvbox-material/blob/53592367dc073cd5b5cbe5b6fae56ad82d0c29f6/colors/gruvbox-material.vim#L90

Try this:

```vim
" Apply custom highlights on colorscheme change.
" Must be declared before executing ':colorscheme'.
augroup custom_highlights_gruvboxmaterial
  autocmd!
  " reset indentline default
  autocmd ColorScheme gruvbox-material 
  \ hi! Conceal ctermbg=NONE guibg=NONE
augroup END

colorscheme gruvbox-material
```

or in Lua

```lua
-- Apply custom highlights on colorscheme change.
-- Must be declared before executing ':colorscheme'.
grpid = vim.api.nvim_create_augroup('custom_highlights_gruvboxmaterial', {})
vim.api.nvim_create_autocmd('ColorScheme', {
  group = grpid,
  pattern = 'gruvbox-material',
  command = -- reset indentline default
            'hi! Conceal ctermbg=NONE guibg=NONE'
})

vim.cmd'colorscheme gruvbox-material'
```

**Comment by leoatchina** [comment]
Should be like this
```
augroup Fix_CocExploererIndentline
    autocmd!
    autocmd ColorScheme gruvbox-material hi! CocExplorerIndentLine ctermbg=NONE guibg=NONE
    autocmd ColorScheme edge             hi! CocExplorerIndentLine ctermbg=NONE guibg=NONE
    autocmd ColorScheme sonokai          hi! CocExplorerIndentLine ctermbg=NONE guibg=NONE
    autocmd ColorScheme everforest       hi! CocExplorerIndentLine ctermbg=NONE guibg=NONE
augroup END
```

**Comment by leoatchina** [comment]
Also fixed vimLineComment bug

```
augroup Fix_CocColorScheme
    autocmd!
    autocmd ColorScheme edge,sonokai,everforest,gruvbox-material autocmd BufWinEnter * hi! vimLineComment ctermbg=NONE guibg=NONE
    autocmd ColorScheme edge,sonokai,everforest,gruvbox-material hi! CocExplorerIndentLine ctermbg=NONE guibg=NONE
augroup END
```

**Comment by antoineco** [comment]
It would be better to fix the `Conceal` highlight group directly like I suggested.

The root cause of your issues is that indenline [hijacks the `Conceal` group](https://github.com/Yggdroot/indentLine/blob/d15d63bf9c4a74a02470d4bc8ecce53df13e3a75/after/plugin/indentLine.vim#L87-L88) (which is a Vim core highlight group and shouldn't be overridden by plugins).
If you fix `Conceal`, you fix all issues at once.

**Comment by leoatchina** [comment]
> 

Actually I have tried to fix `Conceal` group at first bu not work, so I tried CocExplorerIndentLine and it worked
