### ISSUE TITLE
Why not make the functions color something else rather than bold green?

### ISSUE THREAD

**Issue by julkefol** [sainnhe/gruvbox-material#183]
![ezgif com-gif-maker](https://github.com/sainnhe/gruvbox-material/assets/75586433/a639e413-9f36-41e9-9a2d-37a49569b8cb)

It looks nicer I think, because the green is already being used in other parts of the code. So why not use blue or something else?
It's just a humble suggestion. Close it if you think irrelevant. Btw I'm using polyglot vim extension for syntax highlighting.

**Comment by antoineco** [comment]
Because
1. Blue is for _attributes_.
2. Then it wouldn't be gruvbox-material anymore :)

Feel free to add your own customizations on top of the colorscheme based on your preferences.

**Comment by julkefol** [comment]
why wouldn't it be gm anymore? are there any standards maintained for this colo?

**Comment by antoineco** [comment]
That green overall tone is the signature of https://github.com/morhetz/gruvbox, arguably one of the most popular Vim color schemes ever. It's a pretty big ask to demand that something as mundane as functions is highlighted in a different color, considering that it drastically changes the overall aesthetic of the theme.

The semantics of highlight groups is documented in another of sainnhe's color schemes: https://github.com/sainnhe/everforest/blob/master/palette.md#highlights
Porting this document to gruvbox-material is still on my TODO lists, but the semantics are pretty much the same in both of those colorschemes, despite them using different palettes.
