### ISSUE TITLE
Can i change lsp kind colors?

### ISSUE THREAD

**Issue by bty102** [sainnhe/gruvbox-material#193]
I want to change some colors of lsp kind.

**Comment by sainnhe** [comment]
Currently there is not any configuration options that can do this. You can fork this repository or use this piece of code to add your custom highlight groups.

https://github.com/sainnhe/gruvbox-material/blob/7f56d9f9c4860df528031539d321a61f6e081dee/doc/gruvbox-material.txt#L617-L651
