### ISSUE TITLE
Feature request: rainbow headings for markdown with treesitter

### ISSUE THREAD

**Issue by flexagoon** [sainnhe/gruvbox-material#196]
Currently, all headings in Markdown are the same color when using treesitter, but not when using regular highlighting. It would be nice to use rainbow heading with markdown-treesitter as well.

**Comment by antoineco** [comment]
Sounds reasonable 👍 This is achievable by setting the `@markup.heading.1.markdown`, `@markup.heading.2.markdown`, @markup.heading.3.markdown`, etc. highlight groups to different colors.

How it looks with the native Vim syntax, for reference:

![image](https://github.com/sainnhe/gruvbox-material/assets/3299086/b4395db2-fe10-4464-a094-bb3dbc5a5502)

**Comment by bleacheda** [comment]
Hello, not sure if this should now work automatically or I need to manually set the headings colors? And set them to what and how/where?
With tree-sitter enabled I have the same color headings by default.

**Comment by bleacheda** [comment]
Ah, apparently it was because I had `vim.g.gruvbox_material_better_performance = 1` set in my config. Commenting that out fixed it.
I will leave this here in case somebody will stumble upon the same issue.

**Comment by antoineco** [comment]
@bleacheda what does `:set ft?` return in your file?

**Comment by bleacheda** [comment]
It returns: `filetype=markdown`.

**Comment by antoineco** [comment]
Interesting, that's exactly what we have here:
https://github.com/sainnhe/gruvbox-material/blob/1aa1842d80a8845842b9340df2d93683d667247b/colors/gruvbox-material.vim#L1984

I enabled the option in my config, and I can see the correct hightlights, loaded from the `after/syntax` file generated by the `better_performance` option:

<img width="1042" alt="rainbow-md" src="https://github.com/user-attachments/assets/c686af2f-ad76-4c13-8d4d-252c914b0186" />

Possibly something went wrong while generating gruvbox-material's `after/syntax` files.

You could try verifying that `:echo g:colors_name` returns "gruvbox-material". If it does, I'm out of ideas.

**Comment by bleacheda** [comment]
At the moment it works ok for me, with treesitter enabled, all headings have different colors, so I think there is no issue.
It is only when I set `vim.g.gruvbox_material_better_performance = 1` when they all have the same color, the H2 orange.

There is a difference compared to your output though, not sure:

![Image](https://github.com/user-attachments/assets/7868248d-d69d-4ba0-acf7-7d296b96d476)

`:echo g:colors_name` returns "gruvbox-material"
