### ISSUE TITLE
Missing error and warning colors for status

### ISSUE THREAD

**Issue by oblitum** [sainnhe/gruvbox-material#2]
Deep Space is another colorscheme I like very much and it provides colors for warnings and errors, which gruvbox-material lacks. It would be nice to have them added. [Here's example code from Deep Space for that](https://github.com/tyrannicaltoucan/vim-deep-space/blob/master/autoload/lightline/colorscheme/deepspace.vim).

**Comment by oblitum** [comment]
Ah sorry, my bad, there's already. It's just that they have similar background...

**Comment by sainnhe** [comment]
Yes, because there is no darkred/darkyellow in original gruvbox, I think it's better not to add these colors rashly.
