### ISSUE TITLE
Enable markup link group in neorg

### ISSUE THREAD

**Issue by flexagoon** [sainnhe/gruvbox-material#201]
When using https://github.com/nvim-neorg, URLs are not underlined, because Neorg uses the `@markup.link.*` hlgroups for them, but gruvbox-material links them to `markdownUrl`, which is only enabled in Markdown files

**Comment by antoineco** [comment]
>  `markdownUrl` [...] is only enabled in Markdown files

Good point.
I suppose you are enabling `gruvbox_material_better_performance` then?

**Comment by flexagoon** [comment]
Yes, I am
