### ISSUE TITLE
ErrorText highlight looks broken on neovim 0.10

### ISSUE THREAD

**Issue by tranzystorekk** [sainnhe/gruvbox-material#205]
After switching to neovim 0.10, my lsp error highlights started looking weird (the `3600a` text):

![image](https://github.com/sainnhe/gruvbox-material/assets/5671049/f24fb0ef-1e4c-4ada-a161-ee4cef963a9a)

This seems consistent with what gruvbox-material uses with `diagnostic_text_highlight = 1`, but I have that option disabled in the screenshot above.

**Comment by antoineco** [comment]
Could you please share details about your terminal emulator and colorscheme configuration?

Here how the sample code renders for me on WezTerm (latest nightly) with the following colorscheme config (lazy.nvim + Neovim 0.10):

```lua
  {
    "sainnhe/gruvbox-material",
    lazy = false,
    priority = 1000,
    config = function()
      vim.g.gruvbox_material_enable_italic = true
      vim.cmd.colorscheme('gruvbox-material')
    end
  },
```

![image](https://github.com/sainnhe/gruvbox-material/assets/3299086/9baa7740-e718-4485-ae2a-34cb65871a74)

edit: the same as above with `vim.g.gruvbox_material_diagnostic_virtual_text = 'highlighted'`, which you seem to have enabled:

![image](https://github.com/sainnhe/gruvbox-material/assets/3299086/b5cb6d9f-02c2-4923-9fdc-31aa1b8547cb)

**Comment by antoineco** [comment]
Another useful information would be the output of `:Inspect` while the cursor is inside the problematic region. Here is mine for reference:

![image](https://github.com/sainnhe/gruvbox-material/assets/3299086/57635c2d-36b4-42a8-9b05-ec30824a891a)

![image](https://github.com/sainnhe/gruvbox-material/assets/3299086/2a059fa7-3d9e-4e98-8d2a-2d7fbad3d05d)

**Comment by tranzystorekk** [comment]
configuration:

```lua
  {
    "sainnhe/gruvbox-material",
    lazy = false,
    priority = 1000, -- make sure to load this before all the other start plugins
    config = function()
      vim.g.gruvbox_material_background = "hard"
      vim.g.gruvbox_material_ui_contrast = "high"
      vim.g.gruvbox_material_inlay_hints_background = "dimmed"
      vim.g.gruvbox_material_dim_inactive_windows = 1
      vim.g.gruvbox_material_diagnostic_virtual_text = "highlighted"

      -- NOTE: Needs to be called last for the settings to take effect
      vim.cmd.colorscheme("gruvbox-material")
    end,
  },
```

terminal is `wezterm version: 20240203-110809-5046fc22 x86_64-pc-windows-msvc`

`:Inspect`:

![image](https://github.com/sainnhe/gruvbox-material/assets/5671049/5a60b220-5474-4d1c-afb9-0d163f81ad9a)

I checked right now and this doesn't happen on my other `foot` terminal config, so it probably is wezterm specific

**Comment by antoineco** [comment]
What is the output of `echo $TERM` inside your terminal? (outside of Neovim)

Does it also occur if you install and enable the `wezterm` terminfo?

> If you want to get the most application support out of wezterm, then you may wish to install a copy of the `wezterm` TERM definition: [instructions follow]
> -- https://wezfurlong.org/wezterm/config/lua/config/term.html

**Comment by tranzystorekk** [comment]
> Does it also occur if you install and enable the `wezterm` terminfo?

Unfortunately yes, I use Wezterm on Windows to run my WSL2 linux, after adding `config.term = 'wezterm'`, installing `wezterm-terminfo` on WSL and ensuring `echo $TERM` prints `wezterm` **and** that `infocmp` lists wezterm's caps, the issue hasn't changed

**Comment by antoineco** [comment]
I use WezTerm on Windows 11 and run Neovim inside WSL2 (Debian 12) too.

I have to admit that I just ran out of ideas.

**Comment by tranzystorekk** [comment]
I'll try poking around the wezterm community, but thank you for taking the time to help me!

**Comment by tranzystorekk** [comment]
Okay, one more thing I forgot to mention, I'm also using `zellij` in that setup, and indeed when switching it off, the highlight at least doesn't have the background color:

![image](https://github.com/sainnhe/gruvbox-material/assets/5671049/92698e92-2f98-4fa1-96c4-cc893dfcade2)

EDIT: changing zellij configuration to `styled_underlines false` also works around the issue for now

**Comment by antoineco** [comment]
Ah that's some progress!

Support for undercurl on Windows is currently only available in WezTerm _nightly_, so that would explain the absence of undercurl for you.

**Comment by antoineco** [comment]
Cross referencing 
- https://github.com/zellij-org/zellij/issues/3336

**Comment by tranzystorekk** [comment]
Unless you think this report has some other value, I don't think `gruvbox-material` is to blame, so I can close.

**Comment by antoineco** [comment]
I agree that there is probably not much we can do inside the colorscheme, besides changing the default style of diagnostic texts to not use undercurl.
The undercurl was a conscious design decision of sainnhe though, and my preference would be to document how users can ensure that their environment is properly configured to support it.

However, I am interested in the resolution. Terminal multiplexers have been historically problematic with things like italics, standout and fancy underlines. If we can have a note about Zellij inside the vimdoc, I'm all for it!

**Comment by tranzystorekk** [comment]
Hm, I tried to collect info from both wezterm and zellij, and I'm not entirely sure what to make of it:

- zellij has support for [styled_underlines](https://zellij.dev/documentation/options#styled_underlines), barring exceptions if the terminal doesn't cooperate well
- wezterm claims to support those (**on stable** AFAIU) as well in the [FAQ](https://wezfurlong.org/wezterm/faq.html?h=curl#how-do-i-enable-undercurl-curly-underlines), but with the not-entirely-clear note that windows's ConPTY gives some additional trouble

**Comment by antoineco** [comment]
WezTerm has been supporting undercurl for a long time _on Linux and macOS_, but had a dependency on ConPTY and OpenConsole (from Windows Terminal) on Windows, which added support for undercurl [only recently](https://github.com/wez/wezterm/issues/4400#issuecomment-2112402910). Wez included those updated files on Feb. 11, whereas the latest stable was released on Feb. 3.
In case you haven't tried the nightly release, it might be worth giving it a shot (it has been very stable for me so far).

I can't talk authoritatively about Zellij because I have never used it. I remember having a lot of similar issues with Tmux when I wasn't setting the terminfo to `tmux-256color`, but Zellij doesn't seem to require this if I understand correctly.

**Comment by tranzystorekk** [comment]
Some additional tests on `wezterm version: 20240520-135708-b8f94c47 x86_64-pc-windows-msvc` and `zellij 0.40.1`:

zellij disabled, outside of neovim:

![image](https://github.com/sainnhe/gruvbox-material/assets/5671049/17ff65f9-477e-478a-bb79-bd952c318d21)

zellij enabled, outside of neovim:

![image](https://github.com/sainnhe/gruvbox-material/assets/5671049/4032fbb6-c239-4f90-9802-c3d115150a56)

zellij disabled, in neovim:

![image](https://github.com/sainnhe/gruvbox-material/assets/5671049/0c5f13bc-fa68-4e96-80c9-6e7a3a9610b9)

zellij enabled, in neovim:

![image](https://github.com/sainnhe/gruvbox-material/assets/5671049/bde1e6b2-28c2-42b6-af3a-3967f1d0d156)

**Comment by antoineco** [comment]
Looks like Zellij needs to work on its compatibility with Neovim 0.10 🙂
Thanks for sharing the result of your experiments!
