### ISSUE TITLE
 Key not present in Dictionary: "bg_blue"

### ISSUE THREAD

**Issue by AGou-ops** [sainnhe/gruvbox-material#207]
### I have done the following steps before reporting this issue:

- [X] I have searched the existing issues
- [X] I have read the FAQ in the help doc

### Operating system/version

macOS 14.4.1 (23E224)

### Terminal emulator/version

iterm2 3.5.0

### $TERM environment variable

xterm-256color

### Tmux version

tmux 3.4

### Feature matrix

==============================================================================
conform: require("conform.health").check()

conform.nvim report ~
- Log file: /Users/mingday/.local/state/nvim/conform.log
- OK black ready (python)
- OK codespell ready (*)
- OK gofumpt ready (go)
- OK goimports ready (go)
- OK isort ready (python)
- OK jq ready (json)
- OK prettier ready (javascript)
- OK prettierd ready (javascript)
- OK stylua ready (lua)
- OK trim_whitespace ready (_)

==============================================================================
dap: require("dap.health").check()

dap: Adapters ~

dap: Sessions ~
- OK No active sessions

==============================================================================
diffview: require("diffview.health").check()

Checking plugin dependencies ~
- OK nvim-web-devicons installed.

Checking VCS tools ~
- The plugin requires at least one of the supported VCS tools to be valid.
- OK Git found.
- OK Git is up-to-date. (2.39.3)
- WARNING Configured `hg_cmd` is not executable: 'hg'

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found
- WARNING {mason.nvim}: unknown key <check>
- WARNING {mason.nvim}: unknown key <tools>

==============================================================================
lspsaga: require("lspsaga.health").check()

Lspsaga.nvim report ~
- OK `tree-sitter` found 
- OK tree-sitter `markdown` parser found
- OK tree-sitter `markdown_inline` parser found

==============================================================================
luasnip: require("luasnip.health").check()

luasnip ~
- WARNING             For Variable/Placeholder-transformations, luasnip requires
              the jsregexp library. See `:help |luasnip-lsp-snippets-transformations`| for advice
          

==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.10.0
- OK PATH: prepend
- OK Providers: 
    mason.providers.registry-api
    mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2024-05-20-dismal-hub` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- OK wget: `GNU Wget 1.24.5 built on darwin23.2.0.`
- OK curl: `curl 8.8.0 (aarch64-apple-darwin23.4.0) libcurl/8.8.0 (SecureTransport) OpenSSL/3.3.0 zlib/1.2.12 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libssh2/1.11.0 nghttp2/1.61.0 librtmp/2.3 OpenLDAP/2.6.8`
- OK gzip: `Apple gzip 430.100.5`
- OK gtar: `tar (GNU tar) 1.35`
- OK bash: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- WARNING cargo: not available
  - ADVICE:
    - spawn: cargo failed with exit code - and signal -. cargo is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- OK Ruby: `ruby 3.3.1 (2024-04-23 revision c56cd86388) [arm64-darwin23]`
- OK node: `v22.2.0`
- OK Go: `go version go1.22.3 darwin/arm64`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK python: `Python 3.12.3`
- OK npm: `10.7.0`
- OK pip: `pip 24.0 from /opt/homebrew/lib/python3.12/site-packages/pip (python 3.12)`
- OK python venv: `Ok`
- OK java: `openjdk version "21.0.3" 2024-04-16`
- OK javac: `javac 21.0.3`
- OK RubyGem: `3.5.9`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Mon Jun  3 14:18:19 2024.
  Install and authenticate via gh-cli to increase rate limit.

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- $VIMRUNTIME: /usr/local/share/nvim/runtime
- ERROR Found old files in $VIMRUNTIME (this can cause weird behavior):
  /usr/local/share/nvim/runtime/plugin/health.vim
  /usr/local/share/nvim/runtime/autoload/health/provider.vim
  
  - ADVICE:
    - Delete the $VIMRUNTIME directory (or uninstall Nvim), then reinstall Nvim.

Performance ~
- OK Build type: Release

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=^H`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $TERM_PROGRAM="tmux"

tmux ~
- OK escape-time: 10
- OK focus-events: on
- $TERM: xterm-256color
- default-terminal: tmux-256color
- ERROR $TERM differs from the tmux `default-terminal` setting. Colors might look wrong.
  - ADVICE:
    - $TERM may have been set by some rc (.bashrc, .zshrc, ...).

External Tools ~
- OK ripgrep 14.1.0 (/opt/homebrew/bin/rg)

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.6 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v22.2.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.3.9.4)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.4.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ ✓ .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . . . .
  - fish                ✓ ✓ ✓ ✓ ✓
  - gitignore           ✓ . . . .
  - go                  ✓ ✓ ✓ ✓ ✓
  - graphql             ✓ . . ✓ ✓
  - groovy              ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - http                ✓ . . . ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - meson               ✓ . ✓ ✓ ✓
  - ninja               ✓ . ✓ ✓ .
  - nix                 ✓ ✓ ✓ . ✓
  - norg                . . . . .
  - org                 . . . . .
  - php                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - sql                 ✓ . . ✓ ✓
  - svelte              ✓ ✓ ✓ ✓ ✓
  - teal                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vhs                 ✓ . . . .
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - wgsl                ✓ . ✓ ✓ .
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
provider: health#provider#check

Clipboard (optional) ~
- WARNING health#report_start is deprecated, use vim.health.start instead. :help |deprecated|
  Feature will be removed in Nvim 0.11
- OK Clipboard tool found: pbcopy
- WARNING health#report_ok is deprecated, use vim.health.ok instead. :help |deprecated|
  Feature will be removed in Nvim 0.11

Python 3 provider (optional) ~
- Using: g:python3_host_prog = "/opt/homebrew/bin/python3.11"
- WARNING health#report_info is deprecated, use vim.health.info instead. :help |deprecated|
  Feature will be removed in Nvim 0.11
- Executable: /opt/homebrew/bin/python3.11
- Python version: 3.11.9
- pynvim version: 0.5.0
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- Disabled (g:loaded_ruby_provider=0).

Node.js provider (optional) ~
- Disabled (g:loaded_node_provider=0).

Perl provider (optional) ~
- Disabled (g:loaded_perl_provider=0).

==============================================================================
provider.clipboard: require("provider.clipboard.health").check()

Clipboard (optional) ~
- OK Clipboard tool found: pbcopy

==============================================================================
provider.node: require("provider.node.health").check()

Node.js provider (optional) ~
- Disabled (loaded_node_provider=0).

==============================================================================
provider.perl: require("provider.perl.health").check()

Perl provider (optional) ~
- Disabled (loaded_perl_provider=0).

==============================================================================
provider.python: require("provider.python.health").check()

Python 3 provider (optional) ~
- Using: g:python3_host_prog = "/opt/homebrew/bin/python3.11"
- Executable: /opt/homebrew/bin/python3.11
- Python version: 3.11.9
- pynvim version: 0.5.0
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV

==============================================================================
provider.ruby: require("provider.ruby.health").check()

Ruby provider (optional) ~
- Disabled (loaded_ruby_provider=0).

==============================================================================
rainbow-delimiters: require("rainbow-delimiters.health").check()

Custom strategies ~
- OK Valid custom default strategy.
- OK Valid custom strategy for 'vim'.

Custom queries ~

Custom highlight groups ~
- OK Highlight group 'RainbowDelimiterYellow' defined.
- OK Highlight group 'RainbowDelimiterRed' defined.
- OK Highlight group 'RainbowDelimiterOrange' defined.
- OK Highlight group 'RainbowDelimiterBlue' defined.
- OK Highlight group 'RainbowDelimiterGreen' defined.
- OK Highlight group 'RainbowDelimiterViolet' defined.
- OK Highlight group 'RainbowDelimiterCyan' defined.

==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- OK fd: found fd 10.1.0

===== Installed extensions ===== ~

Telescope Extension: `bookmarks` ~
- No healthcheck provided

Telescope Extension: `dap` ~
- No healthcheck provided

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `projects` ~
- No healthcheck provided

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /Users/mingday/.local/state/nvim/lsp.log
- Log size: 9030 KB

vim.lsp: Active Clients ~
- lua_ls (id=1, root_dir=~/.config/nvim, attached_to=[1])

vim.lsp: File watcher ~
- file watching "(workspace/didChangeWatchedFiles)" disabled on all clients

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: bash                 ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/bash.so
- OK Parser: c                    ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/c.so
- OK Parser: cmake                ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/cmake.so
- OK Parser: cpp                  ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/cpp.so
- OK Parser: css                  ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/css.so
- OK Parser: diff                 ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/diff.so
- OK Parser: fish                 ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/fish.so
- OK Parser: gitignore            ABI: 13, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/gitignore.so
- OK Parser: go                   ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/go.so
- OK Parser: graphql              ABI: 13, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/graphql.so
- OK Parser: groovy               ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/groovy.so
- OK Parser: html                 ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/html.so
- OK Parser: http                 ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/http.so
- OK Parser: java                 ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/java.so
- OK Parser: javascript           ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/javascript.so
- OK Parser: jsdoc                ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/jsdoc.so
- OK Parser: json                 ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/json.so
- OK Parser: jsonc                ABI: 13, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/jsonc.so
- OK Parser: latex                ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/latex.so
- OK Parser: lua                  ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/lua.so
- OK Parser: markdown             ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/markdown.so
- OK Parser: markdown_inline      ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/markdown_inline.so
- OK Parser: meson                ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/meson.so
- OK Parser: ninja                ABI: 13, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/ninja.so
- OK Parser: nix                  ABI: 13, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/nix.so
- OK Parser: norg                 ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/norg.so
- OK Parser: org                  ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/org.so
- OK Parser: php                  ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/php.so
- OK Parser: python               ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/python.so
- OK Parser: query                ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/query.so
- OK Parser: regex                ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/regex.so
- OK Parser: rust                 ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/rust.so
- OK Parser: scss                 ABI: 13, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/scss.so
- OK Parser: sql                  ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/sql.so
- OK Parser: svelte               ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/svelte.so
- OK Parser: teal                 ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/teal.so
- OK Parser: toml                 ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/toml.so
- OK Parser: tsx                  ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/tsx.so
- OK Parser: typescript           ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/typescript.so
- OK Parser: vhs                  ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/vhs.so
- OK Parser: vim                  ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/vim.so
- OK Parser: vimdoc               ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/vimdoc.so
- OK Parser: vue                  ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/vue.so
- OK Parser: wgsl                 ABI: 13, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/wgsl.so
- OK Parser: yaml                 ABI: 14, path: /Users/mingday/.local/share/nvim/lazy/nvim-treesitter/parser/yaml.so
- OK Parser: bash                 ABI: 14, path: /usr/local/lib/nvim/parser/bash.so
- OK Parser: c                    ABI: 14, path: /usr/local/lib/nvim/parser/c.so
- OK Parser: lua                  ABI: 14, path: /usr/local/lib/nvim/parser/lua.so
- OK Parser: markdown             ABI: 14, path: /usr/local/lib/nvim/parser/markdown.so
- OK Parser: markdown_inline      ABI: 14, path: /usr/local/lib/nvim/parser/markdown_inline.so
- OK Parser: python               ABI: 14, path: /usr/local/lib/nvim/parser/python.so
- OK Parser: query                ABI: 14, path: /usr/local/lib/nvim/parser/query.so
- OK Parser: vim                  ABI: 14, path: /usr/local/lib/nvim/parser/vim.so
- OK Parser: vimdoc               ABI: 14, path: /usr/local/lib/nvim/parser/vimdoc.so

==============================================================================
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"c"**, lhs: **"W"**
- rhs: `w`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"gp"**
- rhs: `<Cmd>lua require('goto-preview').goto_preview_definition()<CR>`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"d"**
- rhs: `"_d`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"yS"**
- rhs: `<Plug>(nvim-surround-normal-line)`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"ys"**
- rhs: `<Plug>(nvim-surround-normal)`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"c"**
- rhs: `"_c`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"gc"**
- rhs: ` `
- WARNING conflicting keymap exists for mode **"n"**, lhs: **",b"**
- rhs: `:<C-U>LeaderfBuffer<CR>`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **",f"**
- rhs: `:<C-U>LeaderfFile<CR>`

### Minimal vimrc that can reproduce this bug.

```lua
    { ---- colorscheme.
        'sainnhe/gruvbox-material',
        lazy = false, -- make sure we load this during startup if it is your main colorscheme
        priority = 1000, -- make sure to load this before all the other start plugins
        config = function()
            vim.cmd([[
            " https://github.com/sainnhe/gruvbox-material/blob/master/doc/gruvbox-material.txt
            " Important!!
            " For dark version.
            set background=dark
            " Set contrast.
            " This configuration option should be placed before `colorscheme gruvbox-material`.
            " Available values: 'hard', 'medium'(default), 'soft'
            let g:gruvbox_material_background = 'hard'

            let g:gruvbox_material_diagnostic_text_highlight = 1
            " let g:gruvbox_material_diagnostic_line_highlight = 1

            colorscheme gruvbox-material
            ]])
        end,
    },

```

### Steps to reproduce this bug using minimal vimrc

1. update gruvbox-material to latest commit 9169cec4
2. set `gruvbox_material_diagnostic_text_highlight` to 1
3. launch neovim.

### Expected behavior

No error.

### Actual behavior

```
Failed to run `config` for gruvbox-material

vim/_editor.lua:0: /Users/mingday/.config/nvim/init.lua..nvim_exec2() called at /Users/mingday/.config/nvim/init.lua:0../Users/mingday/.local/share/nvim/lazy/gruvbox-material/colors/gruvbox-material.vim,
line 287: Vim(call):E716: Key not present in Dictionary: "bg_blue"

# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
  - lua/plugins/init.lua:7 _in_ **config**
  - lua/config/lazy.lua:17
  - lua/config/init.lua:2
  - init.lua:1
```

**Comment by antoineco** [comment]
Apologies, I broke it with this commit: https://github.com/sainnhe/gruvbox-material/commit/8ca1c0c6d7b8282a01c3404a50c89cb0c0be6fb3
Fixing now. Thanks for reporting!
