### ISSUE TITLE
CtrlP selection is hard to distinguish

### ISSUE THREAD

**Issue by aasutossh** [sainnhe/gruvbox-material#21]
![Screenshot from 2020-02-18 11-58-49](https://user-images.githubusercontent.com/18498932/74708960-131bd180-5246-11ea-8f2b-58de44f100eb.png)
As you can see in screenshot, ctrlp selection is hard to distinguish, in both schemes, light and dark.

**Comment by sainnhe** [comment]
The selected line uses `CursorLine` hi group, which means that the background color of selected line is the same as cursor line.

I slightly increased the contrast of the cursorline. I don't know if it's high enough, you can update this color scheme and get it a try.

**Comment by aasutossh** [comment]
It's definitely better now.
Thanks for being this quick. <3
