### ISSUE TITLE
Trailing whitespace(s) is showing up as orange when it used to gray-ish and less distracting

### ISSUE THREAD

**Issue by CaffeineViking** [sainnhe/gruvbox-material#211]
### I have done the following steps before reporting this issue:

- [X] I have searched the existing issues
- [X] I have read the FAQ in the help doc

### Operating system/version

Windows 10

### GUI client/version

gVim 9.1

### Feature matrix

```
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jul 09 2024 07:07:42)
Included patches: 1-532
Compiled by <https://www.msys2.org/>
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl/dyn          +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3/dyn       +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby/dyn          +wildignore
+cursorbind        -lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             -sound             +xattr
-dnd               -mouseshape        +spell             -xfontset
-ebcdic            +mouse_dec         +startuptime       -xim
+emacs_tags        -mouse_gpm         +statusline        -xpm
+eval              -mouse_jsbterm     -sun_workshop      -xsmp
+ex_extra          +mouse_netterm     +syntax            -xterm_clipboard
+extra_search      +mouse_sgr         +tag_binary        -xterm_save
-farsi             -mouse_sysmouse    -tag_old_static
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
 3rd user vimrc file: "~/.config/vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim91"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -I/usr/include/ncursesw -march=nocona -msahf -mtune=generic -O2 -pipe -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -Wl,--as-needed -o vim.exe -lm -lncursesw -liconv -lacl -lintl
```

### Minimal vimrc that can reproduce this bug.

```
set background=dark
colorscheme gruvbox-material
set list
set listchars=tab:›\ ,trail:•,extends:>,precedes:<,nbsp:_
```

### Steps to reproduce this bug using minimal vimrc

1. Open gVim (or Vim)
2. Set colorscheme to gruvbox-material (dark)
3. Enable "list" to display trailing whitespace
4. Notice trailing whitespace displaying as orange, when it was gray before

### Expected behavior

Trailing whitespace is shown in a "dim" gray. Orange for trailing whitespace is a bit too distracting.

Screenshot below is from `colorscheme gruvbox` since I can't figure out what is causing gruvbox-material to look strange, but this is also how gruvbox-material showed trailing whitespaces not so long ago. I don't know which change caused the issue (and if it was intentional or not). This must be a very recent change, as I did not experience this ~1 or 2 months ago.

![image](https://github.com/user-attachments/assets/1ea53044-e6ac-49d8-b859-1cc1b94e9f8e)

### Actual behavior

Trailing whitespace shows as orange.

![image](https://github.com/user-attachments/assets/c7f1dc7d-7ea9-4350-a4d7-2df50b5334d8)

**Comment by CaffeineViking** [comment]
Feel free to close the issue if the change was intentional.

**Comment by antoineco** [comment]
This change originates from https://github.com/sainnhe/sonokai/issues/104, for context. It was indeed intentional, however `SpecialKey` is _not_ supposed to affect `listchars`.[^1]

[^1]: https://neovim.io/doc/user/syntax.html#hl-SpecialKey

**Comment by antoineco** [comment]
I was able to reproduce, and to find the root cause.

- In Neovim, `listchars` is highlighted by `Whitespace`, whereas `SpecialKey` is reserved for other special characters (mostly escapes like `^M` in files with the DOS file format).
- In Vim, `Whitespace` doesn't exist. `SpecialKey` is used both for the special characters mentioned above and for `listchars`.

This is what trailing whitespaces look like in Neovim both with Neovim's defaults and with the `listchars` from your vimrc:
<img width="729" alt="Screenshot 2024-07-13 at 17 01 09" src="https://github.com/user-attachments/assets/ff4f779a-1dc0-4079-9273-616e68cdcfd6">
<img width="729" alt="Screenshot 2024-07-13 at 17 02 31" src="https://github.com/user-attachments/assets/06cf7366-4d91-4002-9b85-a79988bf6f64">

I'm pushing a fix to `master`. Thanks for reporting! 🙌

**Comment by CaffeineViking** [comment]
Wow, it's already been fixed. Thank you @antoineco!
