### ISSUE TITLE
Vim file part text syntax highlighting is strange

### ISSUE THREAD

**Issue by nibocn** [sainnhe/gruvbox-material#22]
The 'k' of the "dark" keyword is not displayed properly in the screenshot

![image](https://user-images.githubusercontent.com/10879287/75112976-42867000-5684-11ea-80fe-cabd66281bb4.png)

Neovim version:

![image](https://user-images.githubusercontent.com/10879287/75113092-58486500-5685-11ea-804b-3d3e101debbe.png)

**Comment by sainnhe** [comment]
Should be fixed via 3077786.

**Comment by nibocn** [comment]
Test was successful
