### ISSUE TITLE
airline: the specified theme "gruvbox-material" cannot be found

### ISSUE THREAD

**Issue by alex-popov-tech** [sainnhe/gruvbox-material#26]
I see that error when i run `:AirlineTheme gruvbox-material` as said in README :(

**Comment by sainnhe** [comment]
It's not `gruvbox-material`, it's `gruvbox_material`. I have to use underline for some grammatical reasons.

**Comment by alex-popov-tech** [comment]
my bad, thanks for such a nice theme!
