### ISSUE TITLE
Palette Specification (in README?)

### ISSUE THREAD

**Issue by smolck** [sainnhe/gruvbox-material#27]
Hello! I'm looking to port this colorscheme to Emacs, but without a ~showcase/definition (not sure exactly what to call it)~ specification in the README (or elsewhere) of the palette, I have to read through the definitions of the colors in [colors/gruvbox-material.vim](https://github.com/sainnhe/gruvbox-material/blob/master/colors/gruvbox-material.vim). This isn't too bad, but it would be nice to have a ~definition~ specification in the README like Gruvbox does here: https://github.com/gruvbox-community/gruvbox#palette

As an aside, I'd like to say thank you for this great colorscheme! It's probably my most favorite colorscheme I've used with Neovim, and I do tend to miss it when using Emacs (hence why I want to port it over).

EDIT: I think an appropriate name for what I'm thinking of is "specification," so I've modified my comment accordingly.

**Comment by sainnhe** [comment]
One very important reason I don’t do this is that some background colors may changed.

For example, in #21 I changed the color of bg1, and the background colors of popup menu has been adjusted many times.

It's somewhat painful to update the palette in README, I think it should be enough for developers to directly read the source code.

For the definition of color palettes, besides `colors/gruvbox-material.vim`, you can also refer to [vscode](https://github.com/sainnhe/gruvbox-material-vscode/tree/master/src/palette).

The palettes in vscode is not the same as in vim. For example, vscode uses `#202020` as the background color of the hard dark variant while vim uses `#1d2021`. However, the definition in vscode is more detailed.

If you want port to emacs, you can choose the color according to your preference.

**Comment by smolck** [comment]
Thanks for the link to the vscode color scheme! Might end up referring to that for the emacs port, although I've already started referring to the vim color palette so I'll probably stick to that.

Good points on the palette, for sure; if you're changing the colors then it definitely would be a hassle to keep the README updated. I do have one question though; from https://github.com/sainnhe/gruvbox-material/issues/11#issuecomment-564448966:

> v1.0.0 has been released, and the colors will not be adjusted in the future.

What did you mean here?

**Comment by sainnhe** [comment]
This is really embarrassing...

When writing this comment, I thought that all the foreground colors would not be adjusted any more., but I did not expect that I would adjust the background color in the future, because at that time I felt that the background color of the original gruvbox did not need to be adjusted.

I opened #28 , you can subscribe this issue for updates to the palettes.

**Comment by smolck** [comment]
Sorry, didn't mean to embarrass you! Thanks for the clarification.

I've subscribed to #28; thanks for opening the issue!

BTW, you wouldn't mind if I opened an issue for questions on porting this colorscheme to Emacs, would you? I might do so once I've gotten much of it done so I can see what you think and stay as true to this colorscheme as a I can.

**Comment by sainnhe** [comment]
Of course yes!

In addition, you should not follow the principle of "being as consistent as possible with this color scheme" when you port, but do it as appropriate. Since the people using it is you and other emacs users, you can develop as you like.

**Comment by smolck** [comment]
> Of course yes!
> 
> In addition, you should not follow the principle of "being as consistent as possible with this color scheme" when you port, but do it as appropriate. Since the people using it is you and other emacs users, you can develop as you like.

Great, and thanks for the info! I'll close this now.
