### ISSUE TITLE
whitespace / comment is the same color

### ISSUE THREAD

**Issue by breuerfelix** [sainnhe/gruvbox-material#34]
btw i really love this colorscheme! please don't be bothered by my issues, just wanna help optimizing it :)

i like having whitespace visible (setting listchars) and in this colorscheme these got the same colors as the comments which really looks odds.

this is why i got this in my config:
```
highlight NonText guifg=grey25
highlight SpecialKey guifg=grey25
```
maybe it is also intended to have it the same color but i dont remember that other colorschemes do the same (or i just forgot about that)

ofc grey25 is just a placeholder which looks fine to me, feel free to choose something awesome that matches the current comment style :)

just an idea !

i also searched the issues this time and didnt found anything related to that (only that you linked comment to nontext)

**Comment by sainnhe** [comment]
Feedback is always welcome :)

I referred to other color schemes and adjusted `NonText`, `Whitespace` and `SpecialKey`. You can update this color scheme and get it a try.

**Comment by breuerfelix** [comment]
Almost identical with my current changes (grey25). Thanks alot ! looks awesome and cleans up the vimrc again a little bit :)
