### ISSUE TITLE
Support for winbar.

### ISSUE THREAD

**Issue by roachsinai** [sainnhe/gruvbox-material#35]
Thanks for this colorscheme!

I want to know is there any plan for `ToolbarButton` and `ToolbarLine` support? Below pic is screenshot when I using a vim plugin `vimspector` to debug python code.

![image](https://user-images.githubusercontent.com/9500049/79704999-8f826d80-82e6-11ea-8e6d-460aac09842f.png)

And the default color of winbar is not so good, is there any plan to make it consistent with gruvbox? Thanks in advanced.

**Comment by sainnhe** [comment]
Dona via c5483df.

**Comment by roachsinai** [comment]
Thanks a lot!!
