### ISSUE TITLE
Feature request: support more plugins

### ISSUE THREAD

**Issue by zxYin** [sainnhe/gruvbox-material#36]
First of all, thanks for this amazing color scheme. But I found that some highlights of plugins like vim-easymotion and vim-sneak had not been adjusted. I will really appreciate it if you could add them.

**Comment by sainnhe** [comment]
They are already adjusted in [L1676-L1684](https://github.com/sainnhe/gruvbox-material/blob/d4d4f16cf6fd1985cb297bd6e4e20a55281693c4/colors/gruvbox-material.vim#L1676-L1684). If you are not satisfied with this, maybe you can open a PR.

**Comment by zxYin** [comment]
Thanks. I felt that `SneakLabelMask` might be forgotten to set properly (the wield pink color below) and `SneakScope` couldn't be clearly seen in this case.

![image](https://user-images.githubusercontent.com/33487417/80660407-73966e80-8a40-11ea-8013-0e28a85c5b57.png)

Now, I just simply changed it to the following:
```
highlight! SneakLabelMask guibg=#a9b665 guifg=#a9b665 " the green color
highlight! link SneakScope DiffText
highlight! link SneakLabel Search
highlight! link Sneak Search
```
which looked like this:
![image](https://user-images.githubusercontent.com/33487417/80660742-69c13b00-8a41-11ea-9dfe-117a0d876e71.png)

**Comment by sainnhe** [comment]
Thanks for your suggestion, I've adjusted the colors based on your design 4b3f1b8.
