### ISSUE TITLE
Tabline middle background color issues

### ISSUE THREAD

**Issue by zxYin** [sainnhe/gruvbox-material#37]
Hi, a couple of days ago, I changed my status line from airline to lightline. Then, I found the background colors of two middle tabline were different.

This is what the tabline looks like with airline and it's very clear to find the current line:
![image](https://user-images.githubusercontent.com/33487417/80826533-43151880-8b97-11ea-9781-1b0bbb1fb273.png)

However, with lightline, the tabline seems to be one with the current line.
![image](https://user-images.githubusercontent.com/33487417/80826853-c59dd800-8b97-11ea-89ee-921455a7f006.png)

(I changed the both tabsel styles to be unbold, so it might look different with the released version)

I found that the background color set in line 113 of lightline's color scheme was `bg_statusline1`, while in airline's color scheme it was `bg0`

**Comment by sainnhe** [comment]
Thanks for your feedback, the color of airline is incorrect. This should be fixed via 7c1ab60.

**Comment by phortonssf** [comment]
@zxYin how did you get your active buffer to highlight with airline in that image? My active buffer stops highlighting the moment I apply the material gruvebox theme with a clean init.vim and vimrc. Also how did you get the icons in the buffer as well?
