### ISSUE TITLE
Pseudo cursor appear in terminal

### ISSUE THREAD

**Issue by MuhammadMuradG** [sainnhe/gruvbox-material#38]
When I open a terminal with `:terminal` in neovim a pseudo cursor appears, which is made me confusing about which buffer is active in window. As a way to check if I have problem with another plugin and configuration or not, I installed an older version of this plugin, `tag v1.1.1`, and I didn't find this issue. The following is a screen:
![vokoscreen-2020-05-04_16-40-38](https://user-images.githubusercontent.com/50509521/80978300-6816bf00-8e15-11ea-95f9-438fd0388f11.gif)

**Comment by sainnhe** [comment]
Fixed.
