### ISSUE TITLE
Statement on maintenance

### ISSUE THREAD

**Issue by sainnhe** [sainnhe/gruvbox-material#39]
Due to some personal reasons [gruvbox-material#23](https://github.com/sainnhe/gruvbox-material/issues/23#issue-570392877), I'll stop maintaining this project for a period of time(maybe about half a year).

This does not mean that this project has been abandoned, issues and PRs are welcome, I'll review them in the future.

If you're interested in this project and would like to become a maintainer, please [contact me](mailto:sainnhe@gmail.com).

Thanks for your understanding :)

**Comment by sainnhe** [comment]
This project is now maintained by @zxYin .

**Comment by brokenthorn** [comment]
So happy to hear that! This seems to be most maintained gruvbox theme for VSCode right now! The top installed ones are 1 and 2 years old or more! The community should really step in and make this theme more widely known.
