### ISSUE TITLE
Current word setting broken in transparent mode

### ISSUE THREAD

**Issue by Krasjet** [sainnhe/gruvbox-material#41]
![](https://user-images.githubusercontent.com/5229241/82463106-6cd0a980-9a8a-11ea-9719-de0f92704eeb.png)

As seen in the image, the current word highlighting uses the `background` mode instead of `bold` even when the setting is explicitly set.

**Comment by zxYin** [comment]
Which plugin did you use?

**Comment by Krasjet** [comment]
I'm using [vim-illuminate](https://github.com/RRethy/vim-illuminate). I did a git bisect and the commit that causes the problem is de9b4dc4b5a917c3aecd72adb033e792b85da273.

**Comment by zxYin** [comment]
Thanks. It should be fixed via  66fc53fa443d40abb14ddf484f7cff267d5c6da6.
