### ISSUE TITLE
Diferente colors brackets close tags

### ISSUE THREAD

**Issue by llmdev** [sainnhe/gruvbox-material#42]
Hi,

I have a problem with tsx files, the closing of the tags are with different colors in the bracket.

use polyglot for syntax

![Captura de Tela 2020-06-04 às 16 04 16](https://user-images.githubusercontent.com/25234963/83800204-7444a500-a67d-11ea-8c26-f5a6174d1c24.png)

**Comment by zxYin** [comment]
Hi, most of color schemes are using different colors for tags, because it's easy for you to distinguish them. If you want to make them the same color, you can add `hi! link jsxOpenPunct blue` or `hi! link jsxClosePunct green` to your vimrc
