### ISSUE TITLE
Wrong background color for Lightline

### ISSUE THREAD

**Issue by DrunkenMoogle** [sainnhe/gruvbox-material#43]
Lightline uses the light background color despite being set to dark. 
![LightlineColor](https://user-images.githubusercontent.com/67517613/85928781-a95ba600-b87d-11ea-9c5c-eec015a8b595.png)

**Comment by sainnhe** [comment]
I can't reproduce it using your init.vim in my neovim. Did you set the background to dark when nvim is running? Lightline won't reload the color scheme after a color scheme is applied.

**Comment by DrunkenMoogle** [comment]
After some looking around it turns out that I was running a very old version of neovim via Ubuntu 18.04 LTS on WSL. After updating to a newer version the issue resolved itself.
