### ISSUE TITLE
Request: Add option to dim unused import instead of underline

### ISSUE THREAD

**Issue by wweitzel** [sainnhe/gruvbox-material#44]
<img width="1135" alt="Screen Shot 2020-07-02 at 9 22 04 PM" src="https://user-images.githubusercontent.com/17417149/86422161-57b28180-bcaa-11ea-87b1-c9166a9bf8ca.png">

Currently unused imports will show a dashed underline (see image above). I would like an option in the settings to have the font be dimmed slightly, instead of showing the underline.

**Comment by sainnhe** [comment]
This is the repository for vim, you should not open an issue here.

Done via  [9a18931](https://github.com/sainnhe/gruvbox-material-vscode/commit/9a18931767f9ac87930931ac9eb98936078dfa87), now this color scheme will dim unnecessary code.

**Comment by wweitzel** [comment]
Whoops. Sorry about that!
