### ISSUE TITLE
# %% not recognized as comment

### ISSUE THREAD

**Issue by roachsinai** [sainnhe/gruvbox-material#45]
![image](https://user-images.githubusercontent.com/9500049/86901975-e9edd600-c13f-11ea-89fe-84b3755d0e79.png)

Output of `hi Comment`:

```
:hi Comment
Comment        xxx term=bold cterm=italic ctermfg=245 gui=italic guifg=#928374
```

**Comment by zxYin** [comment]
Which highlight plug did you use? I think it might be its bug.

**Comment by roachsinai** [comment]
```
hmanx ~/tt » cat ~/.vimrc                
" 定义快捷键的前缀，即<Leader>
let mapleader=" "
call plug#begin('~/.vim/plugged')
Plug 'nightsense/cosmic_latte' | Plug 'sainnhe/gruvbox-material'
call plug#end()




let g:gruvbox_material_background = 'soft'
set background=dark
colorscheme gruvbox-material
```

setting above still have this issue.

**Comment by zxYin** [comment]
I couldn't reproduce your bug. Maybe you can try to add `syntax on` into your `.vimrc` or you can install a python syntax highlighting plug, for example, [vim-polyglot](https://github.com/sheerun/vim-polyglot)

**Comment by roachsinai** [comment]
@zxYin Thanks for reply, add found I have a match for `# %%` in `syntax` folder.
