### ISSUE TITLE
[Question] Hex codes of the colors?

### ISSUE THREAD

**Issue by chinleung** [sainnhe/gruvbox-material#46]
Hi,

Is there a place where I could get the hex codes of the colors for material medium dark background?

I'm trying to synchronize them with my iTerm color palette.

I'm looking for something like this: https://github.com/morhetz/gruvbox/blob/master/gruvbox_256palette_osx.sh

Thanks

**Comment by sainnhe** [comment]
See this [wiki page](https://github.com/sainnhe/gruvbox-material/wiki/Related-Projects).
