### ISSUE TITLE
[help] how to override highlight group Conceal values set by gruvbox-material

### ISSUE THREAD

**Issue by roachsinai** [sainnhe/gruvbox-material#47]
Hi there, I wanna Custom `Conceal` group highlights.

What I've tried is create a file named `filetype.vim` under `~/.vim/after/plugin` with contents:

```
if &background == 'light'
    if g:colors_name == 'bluewery-light'
        highlight Conceal cterm=NONE guifg=#bbbbbb
    else
        highlight Conceal cterm=NONE guifg=#ccdd88
    endif
else
    highlight Conceal gui=NONE guifg=#364954
endif
```

I found gruvbox-material override my custom in fact which is in contrary.

So how to make it?

Thanks in advace!

**Comment by zxYin** [comment]
It's not a good idea to change the plugin's code directly, because you may not get any updates. You should write your custom settings in your `vimrc`.

**Comment by roachsinai** [comment]
Setting in vimrc not work, plugin is load after vimrc (will cover the my custom).
In my mind, setting in `after` directory should work, but failed too.

**Comment by zxYin** [comment]
Which plugin will load after vimrc? Gruvbox-material? I just added `highlight Conceal cterm=NONE guifg=#bbbbbb` in my vimrc and it worked.

**Comment by roachsinai** [comment]
Custom in vimrc directly not work for me. So maybe that's the problem of my vim settings in vimrc. I'll try to find a minimal vimrc to reproduce.

**Comment by roachsinai** [comment]
@zxYin Thanks for your reply. Maybe something wierd with `indentLine` plugin for my setting: https://github.com/Yggdroot/indentLine/issues/57#issuecomment-672513859

**Comment by roachsinai** [comment]
> Which plugin will load after vimrc? Gruvbox-material? I just added `highlight Conceal cterm=NONE guifg=#bbbbbb` in my vimrc and it worked.

Hi I just found this issue is caused by code of this plugin here: https://github.com/sainnhe/gruvbox-material/blob/4f98272fdbf9a53942eceb1aaeefb19e4f6b63bb/colors/gruvbox-material.vim#L574

the setting of indentLine of gruvbox-material will let the Conceal highlight always to those value gruvbox-material sets which override indentLight's default settings. Even after I switch colorscheme.

https://github.com/Yggdroot/indentLine/issues/57

**Comment by roachsinai** [comment]
Maybe it's not a better idea to add setting of other plugin? So please make a declaration and add a on-off switch to enable only use indentLine default setting not involv settings of gruvbox-material.

**Comment by zxYin** [comment]
> > Which plugin will load after vimrc? Gruvbox-material? I just added `highlight Conceal cterm=NONE guifg=#bbbbbb` in my vimrc and it worked.
> 
> Hi I just found this issue is caused by code of this plugin here:
> 
> https://github.com/sainnhe/gruvbox-material/blob/4f98272fdbf9a53942eceb1aaeefb19e4f6b63bb/colors/gruvbox-material.vim#L574
> 
> the setting of indentLine of gruvbox-material will let the Conceal highlight always to those value gruvbox-material sets which override indentLight's default settings. Even after I switch colorscheme.
> 
> [Yggdroot/indentLine#57](https://github.com/Yggdroot/indentLine/issues/57)

This is a shortcoming of `indentLine` not `gruvbox-material` and it says to use `g:indentLine_color_gui` or `g:indentLine_color_term` to set the color in its doc. I just tried this simple `vimrc`.
```
call plug#begin('~/.vim/plugged')
  Plug 'Yggdroot/indentLine'
call plug#end()
highlight Conceal guifg=#bbbbbb
```
And the `Conceal` doesn't set to `#bbbbbb` either.

Because of https://github.com/Yggdroot/indentLine/blob/43dbd7092801637972b1d9fcecaaeee11f8e00cf/after/plugin/indentLine.vim#L70
if you don't set the color by using its specific syntax, the `Conceal` will become the default color which is set by the color scheme.

**Comment by roachsinai** [comment]
Yeah, that's right. So to avoid that I have to custom `g:indentLine_color_gui` after `colorscheme gruvbox-material`, add not switch to colorschemes that not setting `g:indentLine_color_gui` by colorscheme itself...

**Comment by zxYin** [comment]
Hmm, actually, I cannot understand what you meant and what you did. I think the goal of color scheme is to design a group of uniform colors for vim, as well as plugins. If you want to do some custom changes, I think it's ok to add `highlight` or `indentLine_color` in your `vimrc`, even if you just want its default colors.

**Comment by roachsinai** [comment]
Sure, and thanks for this colorscheme!
