### ISSUE TITLE
How to change background color only?

### ISSUE THREAD

**Issue by numToStr** [sainnhe/gruvbox-material#48]
Is there any simple way to change only the background color? Or Adding every color definition in the custom palette is the only to change the background color.

PS: Thank you for making this color scheme. It is the best :heart:.

**Comment by zxYin** [comment]
There is guidance in FAQ at `README.md`. You can try:

```
augroup GruvboxMaterialCustom
  autocmd!
  autocmd ColorScheme gruvbox-material highlight Normal guibg={your color} ctermbg={your color}
augroup END

colorscheme gruvbox-material
```

If you want to change multiple colors, you can try:

```
augroup GruvboxMaterialCustom
  autocmd!
  autocmd ColorScheme gruvbox-material call SetColorOptions()
  function SetColorOptions()
    highlight Normal guibg={your color} ctermbg={your color}
    highlight NonText guibg={your color} ctermbg={your color}
  endfunction
augroup END

colorscheme gruvbox-material
```

 Or, there is a simplest way:

```
colorscheme gruvbox-material
highlight Normal guibg={your color} ctermbg={your color}
```

PS: Pay attention to the declared position of the color scheme

**Comment by numToStr** [comment]
@zxYin Thank you for your explanation.

But after setting the `Normal` and  `NonText` color, I am getting this weird weird colors
```vim
augroup GruvboxMaterialCustom
  autocmd!
  autocmd ColorScheme gruvbox-material call SetColorOptions()
  function SetColorOptions()
    highlight Normal guibg=#121212 ctermbg=233
    highlight NonText guibg=#121212 ctermbg=233
  endfunction
augroup END
```

![image](https://user-images.githubusercontent.com/24727447/90593710-40056d00-e206-11ea-91e2-8b875dfeedce.png)

**Comment by zxYin** [comment]
`#121212` is the black background color you set, although only a small part. BTW, the `guibg` and `ctermbg` of `Normal` are the color of the background. In this case, you don't need to set `NonText`

**Comment by numToStr** [comment]
I thought `NonText` will fix this weird color issue. But no luck.

**Comment by zxYin** [comment]
If you want to change the lighter part, you can try:
` highlight EndOfBuffer guibg=#121212 ctermbg=233`. Thus, your final settings should be:

```vim
augroup GruvboxMaterialCustom
  autocmd!
  autocmd ColorScheme gruvbox-material call SetColorOptions()
  function SetColorOptions()
    highlight Normal guibg=#121212 ctermbg=233
    highlight EndOfBuffer guibg=#121212 ctermbg=233
  endfunction
augroup END
```

**Comment by numToStr** [comment]
> ```viml
> augroup GruvboxMaterialCustom
>   autocmd!
>   autocmd ColorScheme gruvbox-material call SetColorOptions()
>   function SetColorOptions()
>     highlight Normal guibg=#121212 ctermbg=233
>     highlight EndOfBuffer guibg=#121212 ctermbg=233
>   endfunction
> augroup END
> ```
Thanks man. This does the trick.

I guess this will be out of the scope. But can you provide a config option to change the background like transparent background config?

**Comment by zxYin** [comment]
You can try:

```vim
augroup GruvboxMaterialCustom
  autocmd!
  autocmd ColorScheme gruvbox-material call SetColorOptions()
  function SetColorOptions()
    highlight Normal guibg=none
    highlight EndOfBuffer guibg=none
  endfunction
augroup END
```

**Comment by numToStr** [comment]
That's not what I meant. I mean something like this `let g:gruvbox_material_background_color = ['#121212', 233]`.

**Comment by zxYin** [comment]
We think it is not necessary, because there are thousands of colors in the color scheme including the UI, Plugins, etc. If users want to custom some of them, it's easy to put them into their `vimrc`.

**Comment by numToStr** [comment]
I understand that. And thanks for helping me :v: .
