### ISSUE TITLE
Neovim LSP diagnostics integration

### ISSUE THREAD

**Issue by lucastrvsn** [sainnhe/gruvbox-material#51]
Neovim built-in LSP diagnostics finally [merged](https://github.com/neovim/neovim/pull/12655) into neovim core and its API is stable now. Can we implement some highlight groups for the new neovim lsp?

I made some examples of how it will work and for me it's nice and clean!

```vim
call gruvbox_material#highlight('LspDiagnosticsFloatingError', s:palette.red, s:palette.bg3)
call gruvbox_material#highlight('LspDiagnosticsFloatingWarning', s:palette.yellow, s:palette.bg3)
call gruvbox_material#highlight('LspDiagnosticsFloatingInformation', s:palette.blue, s:palette.bg3)
call gruvbox_material#highlight('LspDiagnosticsFloatingHint', s:palette.aqua, s:palette.bg3)

highlight! link LspDiagnosticsDefaultError ErrorLine
highlight! link LspDiagnosticsDefaultWarning WarningLine
highlight! link LspDiagnosticsDefaultInformation InfoLine
highlight! link LspDiagnosticsDefaultHint HintLine

highlight! link LspDiagnosticsVirtualTextError Grey
highlight! link LspDiagnosticsVirtualTextWarning Grey
highlight! link LspDiagnosticsVirtualTextInformation Grey
highlight! link LspDiagnosticsVirtualTextHint Grey

highlight! link LspDiagnosticsUnderlineError ErrorLine
highlight! link LspDiagnosticsUnderlineWarning WarningLine
highlight! link LspDiagnosticsUnderlineInformation InfoLine
highlight! link LspDiagnosticsUnderlineHint HintLine

highlight! link LspDiagnosticsSignError RedSign
highlight! link LspDiagnosticsSignWarning YellowSign
highlight! link LspDiagnosticsSignInformation BlueSign
highlight! link LspDiagnosticsSignHint AquaSign
```

I don't know if I'm right with all this hi group links but, for me, works really well. I can make a PR to add this!

Thanks so much for this colorscheme, it's my daily driver for a long time!

**Comment by sainnhe** [comment]
It seems that there is no problem with these codes.

Go ahead and add them in [L143](https://github.com/sainnhe/gruvbox-material/blob/4602d8e4dd73d3f2cbbd6635d4c27d4ebd0a11fb/colors/gruvbox-material.vim#L143), I'm going to merge it. Don't forget to remove empty lines in your code coz I want to make the code compact.
