### ISSUE TITLE
Why some words are red while others are not?

### ISSUE THREAD

**Issue by atlas-comstock** [sainnhe/gruvbox-material#57]
![image](https://user-images.githubusercontent.com/7270555/100586096-94ea7080-3329-11eb-85cf-49c6fed81a2e.png)

![image](https://user-images.githubusercontent.com/7270555/100586122-9d42ab80-3329-11eb-8da2-d0a17f8d4ecd.png)

For example, `checkTaskStatus` is red in the sentence.

**Comment by sainnhe** [comment]
The words are also underlined, and all of them are in a string.

Did you setup a linter that will lint grammatical errors?

Btw, please follow the [issue template](https://github.com/sainnhe/gruvbox-material/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), otherwise I can't reproduce this bug.

**Comment by atlas-comstock** [comment]
@sainnhe  hi, thanks for the clarfication.

It is caused by vim-go 's 
```
Highlight spelling errors in strings when |spell| is enabled.
>
  let g:go_highlight_string_spellcheck = 1
<
                                             *'g:go_highlight_format_strings'*
```
