### ISSUE TITLE
Support vimtex 2.0

### ISSUE THREAD

**Issue by j1-lee** [sainnhe/gruvbox-material#66]
- Operating system/version: Ubuntu Mate 20.04
- Terminal emulator/version: mate-terminal 1.24.0
- `echo $TERM`: xterm-256color
- `vim --version` or `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Minimal vimrc that can reproduce this bug
**minimal.vim**
```vim
" vimtex version >= 2.0
" https://github.com/lervag/vimtex/releases/tag/v2.0
call plug#begin()
Plug 'sainnhe/gruvbox-material'
Plug 'lervag/vimtex'
call plug#end()

set termguicolors
let g:gruvbox_material_enable_italic = 1
colorscheme gruvbox-material
```

### Steps to reproduce this bug using minimal vimrc
Run `vim foo.tex -u minimal.vim`, while having a recent version of [lervag/vimtex](https://github.com/lervag/vimtex).

### Actual behaviour
First, thank you for this wonderful plugin. I've tried several other colorschemes out there, but this is my favorite.

This is not a bug report, but rather a feature request. Vimtex recently added (since [v2.0](https://github.com/lervag/vimtex/releases/tag/v2.0)) a new syntax support, departing from the traditional Dr. Chip's `tex` syntax.

As we can see from the picture below, the highlighting is _broken_ due to new highlight groups introduced by vimtex.

![Screenshot at 2020-12-31 01-08-57](https://user-images.githubusercontent.com/47399860/103397166-1db12380-4b05-11eb-85f9-0eb50c8a2417.png)

(I'll attach the `tex` file at the bottom, in case you want to reproduce it.)

### Expected behaviour
Well, a sane highlights.

One may turn off the new syntax feature provided by vimtex, by including `let g:vimtex_syntax_enabled = 0`, which would revert the highlighting back to what it used to be:
![Screenshot at 2020-12-31 01-09-58](https://user-images.githubusercontent.com/47399860/103397230-6cf75400-4b05-11eb-9611-9b19f6e75b22.png)

But as vimtex is a very popular tex-plugin, I hope gruvbox-material adds support for the new version of vimtex.

Fortunately the new highlight groups do not overlap the old ones that are highlighted by gruvbox-material (e.g., vimtex does not use a traditional hl-group `texStatement`; now `texCmd` replaces its role). So this new feature, I guess, can be safely implemented. For example, when I add
```vim
" lervag/vimtex {{{
highlight! link texCmd Green
highlight! link texCmdClass Purple
highlight! link texCmdTitle Purple
highlight! link texCmdAuthor Purple
highlight! link texCmdPart Purple
highlight! link texCmdBib Purple
highlight! link texCmdPackage Yellow
highlight! link texCmdNew Yellow
highlight! link texArgNew Orange
highlight! link texPartArgTitle BlueItalic
highlight! link texFileArg BlueItalic
highlight! link texEnvArgName BlueItalic
highlight! link texMathEnvArgName BlueItalic
highlight! link texTitleArg BlueItalic
highlight! link texAuthorArg BlueItalic
" }}}
```
into `colors/gruvbox-material.vim` (in the gruvbox-material plugin directory), the result is as follows:
![Screenshot at 2020-12-31 01-11-03](https://user-images.githubusercontent.com/47399860/103397550-e6dc0d00-4b06-11eb-8f0f-038a5da5ca80.png)

I've checked that the screenshot above with `g:vimtex_syntax_enabled = 0` remains the same whether or not I include these lines---i.e., the new highlight groups do not seem to interfere with the old ones.

I provided the sample highlight links (to specific colors) as above, in order to just show you new highlight groups you might want to consider; I am totally fine if you linked the groups to other colors. I just wish gruvbox-material can give the users a nice default set of colors.

Thank you again for the great colorscheme!

**foo.tex** (a LaTeX file used above)
```tex
\documentclass{article}

\title{Hello, world}
\author{Jaewon Lee}

\usepackage{amsmath,amssymb,amsthm}
\usepackage[margin=1.5in]{geometry}
\usepackage{setspace}\onehalfspacing

\let\hat\widehat
\def\myname{Jaewon}
\newcommand{\norm}[1]{\lvert #1 \rVert}
\DeclareMathOperator*{\argmax}{argmax}

\begin{document}
\maketitle

\section{Introduction}
This is a \LaTeX document. For all $n > 2$, there are no $a, b, c \in \mathbb{N}$ such that
\begin{displaymath}
  a^n + b^n = c^n.
\end{displaymath}
\begin{center}
  By the way, colorless green ideas sleep furiously.
\end{center}
\end{document}
```

**Comment by sainnhe** [comment]
Thank you! I'm going to use your code directly https://github.com/sainnhe/gruvbox-material/commit/46b5409c5fad494b2ed96a5145e3c50f63c067e1. Btw, feel free to open a PR next time ;)
