### ISSUE TITLE
Include after/diff/gruvbox_material.vim in after/gitcommit/gruvbox_material.vim

### ISSUE THREAD

**Issue by subnut** [sainnhe/gruvbox-material#70]
When you run `git commit -v`, it includes the diff of the commit in the `COMMIT_EDITMSG`.
Due to current configuration, the diff appears in yellow and aqua colors! Not Pleasant At All.

Please include `diff` highlights in `gitcommit` too. Thanks.

**Comment by sainnhe** [comment]
Done via 727f2b2.
