### ISSUE TITLE
Doesn't work in NeoVim

### ISSUE THREAD

**Issue by kdnfgc** [sainnhe/gruvbox-material#71]
When I plugged in this theme while configuring NeoVim, the theme didn't appear. I don't know if this is a personal issue, or if the code just isn't meant to work in NeoVim. No matter the case, I find that this is an important issue to address, especially since NeoVim is becoming increasingly popular.

**Comment by sainnhe** [comment]
Can't reproduce. Please follow the [issue template](https://raw.githubusercontent.com/sainnhe/gruvbox-material/master/.github/ISSUE_TEMPLATE/bug_report.md) to provide enough information.

**Comment by kdnfgc** [comment]
Sorry, I couldn't reproduce the issue either. I eventually got it working.
