### ISSUE TITLE
Add option to disable the Cursor highlights

### ISSUE THREAD

**Issue by ndavd** [sainnhe/gruvbox-material#72]
gruvbox-material is overriding my Cursor highlight. Is there a way to disable the cursor highlighting made by gruvbox-material?

**Comment by sainnhe** [comment]
I don't know what you mean by cursor highlight, could you share your related configuration?

**Comment by ndavd** [comment]
I meant the `g:gruvbox_material_cursor` option. I have my custom highlights in the plugin/ directory and I have `hi Cursor guibg=white` there but when I load neovim the Cursor is the same color as the text's foreground (reverse)

**Comment by sainnhe** [comment]
See FAQ section in help doc, there is something like "How to use custom colors?". I'd suggest you to use autocmd to highlight the `Cursor` hi group.

**Comment by ndavd** [comment]
Alright thanks! Closing this
