### ISSUE TITLE
Setting g:gruvbox_material_better_performance=1 links StartifyHeader to Orange

### ISSUE THREAD

**Issue by ndavd** [sainnhe/gruvbox-material#74]
Is this normal behavior?
Without setting the option I have:
`StartifyHeader guifg=#d4d4d4`
But with that option enabled:
`StartifyHeader guifg=#d4d4d4 links to Orange`

**Comment by sainnhe** [comment]
`StartifyHeader` should be linked to `Orange` regardless of whether `g:gruvbox_material_better_performance` is set.

> Without setting the option I have:
> StartifyHeader guifg=#d4d4d4

This is unexpected, could you please follow the [issue template](https://github.com/sainnhe/gruvbox-material/raw/master/.github/ISSUE_TEMPLATE/bug_report.md) to provide minimal vimrc and steps to reproduce this bug?

**Comment by ndavd** [comment]
So then it's probably due to my config. I have a colors.vim in autoload that is called in plugin. https://paste.sh/BQGSWC55#9xebSvlsIHfnNsYyt7xsdnCv

(it's probably not worth to make a minimal reproduce, since the problem is probably related to colors.vim)

**Comment by ndavd** [comment]
Question: Why did you make the colorscheme in a way that in order to change a highlight you have to call a function?

**Comment by sainnhe** [comment]
Because the color palette is too complex, see gruvbox_material#get_palette()

**Comment by ndavd** [comment]
The thing is. If I set the better performance option I can't seem to override that highlight. I tried hi! link Statusline NONE

**Comment by sainnhe** [comment]
See FAQ "How to use custom colors?"

**Comment by ndavd** [comment]
I did and it worked for other colors. I have pasted my colors.vim here https://paste.sh/BQGSWC55#9xebSvlsIHfnNsYyt7xsdnCv

**Comment by sainnhe** [comment]
So what's your question? What should I do with your colors.vim?

**Comment by ndavd** [comment]
It was just for you to take a look. If I don't set the performance option my StartifyHeader highlight works how I define it but if I set that better performance option it links it to Orange. And even when I link it to none how it is explained FAQ, it stays Orange nonetheless

**Comment by ndavd** [comment]
I'll try to make a reproduce I guess

**Comment by ndavd** [comment]
The problem is probably related to my config. Closing this.
