### ISSUE TITLE
Use mix palette

### ISSUE THREAD

**Issue by ghost** [sainnhe/gruvbox-material#79]
Hello there! I want to switch the palette of Mix, but I can't find any documentation to switch it, what should I do？
![Screenshot_20210504_215210](https://user-images.githubusercontent.com/83487691/117014060-02f4f280-ad23-11eb-9535-07c9b4036fd3.jpg)

**Comment by sainnhe** [comment]
I really hope people can read the [README](https://github.com/sainnhe/gruvbox-material#usage) before asking any questions.

**Comment by sainnhe** [comment]
I think I should remove the installation section in README so people will only notice the help doc.

**Comment by ghost** [comment]
> 我认为我应该删除自述文件中的安装部分，这样人们才会注意到帮助文档。

Sorry, sir, my problem has been solved, thank you very much :-)
