### ISSUE TITLE
Bad contrast in lightline

### ISSUE THREAD

**Issue by h0adp0re** [sainnhe/gruvbox-material#80]
- Operating system/version: macOS Big Sur 11.3
- Terminal emulator/version: alacritty 0.7.2 (5ac8060)
- `echo $TERM`: screen-256color
- `tmux -V`: 3.2
- `nvim --version`: v0.5.0-dev+nightly-39-g8a93d1028

### Actual behaviour

<img width="188" alt="Screenshot 2021-05-07 at 01 05 25" src="https://user-images.githubusercontent.com/11251772/117372116-b13e9a80-aed1-11eb-8cf1-965e279bc17f.png">

### Expected behaviour

Previously the filename was colored just like the `1` after `dotfiles` in the tmux statusbar. This all changed with the latest update (e864b544c98402dfd4dec5996be51cc5bd63bfdd). It's really hard to read without changing terminal font size to 200% now. Is there any way to revert or overwrite these colors?

I love this colorscheme, I'd hate to start looking for another if there are too many regressions.

**Comment by sainnhe** [comment]
It's my fault, I shouldn't set is as default.

This should be fixed via 9371541.

**Comment by h0adp0re** [comment]
Oh, I'm glad to hear this wasn't intentional. Thanks for reacting promptly!
