### ISSUE TITLE
Change Treesitter TSPunctSpecial (issue with Latex)

### ISSUE THREAD

**Issue by lambtho12** [sainnhe/gruvbox-material#81]
The current value for nvim-treesitter's TSPunctSpecial is set to foreground color (fg).

This is problematic when working on latex (`.tex`) documents, as nvim-treesitter [defines the command ``\item`` as special punctuation](https://github.com/nvim-treesitter/nvim-treesitter/blob/ddc0f1b606472b6a1ab85ee9becfd4877507627d/queries/latex/highlights.scm#L81).
Therefore in the following example
```tex
\begin{itemize}
\item My first item
\item My second item
\item My third item
\end{itemize}
```
the commands are not different than the plain text.

I am not sure if this would be considered a big deal to change it here, or check with treesitter if the `\item` command should be associated to something else than special punctuation.

Note that this issue is specific to gruvbox-material. I tested several other themes (built-in neovim) and none showed the same issue.

I think that the color `Blue` may fit here, as it is almost not used in any other treesitter highlight groups.

**Comment by sainnhe** [comment]
Should be fixed now.
