### ISSUE TITLE
[Suggestion] Change some highlights to be able to better differentiate between different builtins/keywords in languages.

### ISSUE THREAD

**Issue by ghost** [sainnhe/gruvbox-material#83]
![image](https://user-images.githubusercontent.com/67145097/118095297-854d7880-b3ed-11eb-9d5f-505af4f9fc25.png)
I am using Treesitter with neovim at the moment, and it looks absolutely great.

However, as you can see in the screenshot, the highlight colour for `import`, `None`, `self`, constants(snake case variables) and numbers is the same even though they all are different things. Is it possible to change the highlight colour of these to be different from each other to improve readability?

This is also the case for lua for example, where `nil`, `1`, and booleans all have the same highlight colour(purple).

Also, mabye `__init__()` can be highlighted in a blue since it is a special method in python.

**Comment by sainnhe** [comment]
This color scheme has been optimized for about 90 file types and plugins, but I personally don't use most of them in my daily development, that means they are only basically optimized and guaranteed to work.

So as tree-sitter, I personally don't use it, there might be some bugs and flaws.

If you are a user of tree-sitter, could you help me optimize it? You can adjust the design that you feel is flawed. Maybe fork this repo and create a PR. Here is the related code for tree-sitter:

https://github.com/sainnhe/gruvbox-material/blob/82c696585d9d7a72596d34a755a6080836ae6561/colors/gruvbox-material.vim#L398-L445

**Comment by ghost** [comment]
Oh I see, that's understandable.

> If you are a user of tree-sitter, could you help me optimize it?
You can adjust the design that you feel is flawed.

Alright, that's fine, I'll try to make a PR with some colours adjusted.

**Comment by sainnhe** [comment]
Fixed via e128629.
