### ISSUE TITLE
[Suggestion] Enable bold and italic by default if running in a GUI or if termguicolors is enabled

### ISSUE THREAD

**Issue by ghost** [sainnhe/gruvbox-material#90]
I feel like if you are running a colorscheme like gruvbox with `termguicolors` or in a GUI, the odds are that your terminal/GUI supports bold and italic.

I also feel like bold and italic are important in the colorscheme, and hence they should be enabled by default if running in a GUI env or if `termguicolors` are enabled.

I think this is better default behavior, however if there is a reason it is not or if you do not feel the same due to another reason, feel free to close this! It is after all opinionated.

**Comment by sainnhe** [comment]
> I also feel like bold and italic are important in the colorscheme

I don't think so. IMO Italic and bold will make your code looks untidy.

The defaults can't satisfy everyone, that's why we need configuration options.
