### ISSUE TITLE
NodeJS undefined outputs are invisible

### ISSUE THREAD

**Issue by iCromix** [sainnhe/gruvbox-material#94]
- Operating system/version: Windows 11 Build 22000.71
- Terminal emulator/version: nvim-qt
- `vim --version` or `nvim --version`: NVIM v0.5.0-dev+1459-g384f9870f

### Minimal vimrc that can reproduce this bug

```vim
call plug#begin('~/AppData/Local/nvim/plugged')
    Plug 'sainnhe/gruvbox-material'
call plug#end()

let g:gruvbox_material_background = 'soft'

colorscheme gruvbox-material
```

### Steps to reproduce this bug using minimal vimrc

Create a JS file with

```js
// File.js
console.log(undefined);
```
Open a `:terminal` and run `node File.js`

### Actual behaviour
<img src="https://i.imgur.com/plHyeTv.gif" alt="issue-gif">

### Expected behaviour

Beign able to see `undefined` printed on the console

**Comment by sainnhe** [comment]
Should be fixed via https://github.com/sainnhe/gruvbox-material/commit/5cf1ae0742a24c73f29cbffc308c6f5576404e60
