### ISSUE TITLE
Highlight linking of TSError

### ISSUE THREAD

**Issue by MuhammadMuradG** [sainnhe/gruvbox-material#95]
I don't know if linking `TSError` to `ErrorText` is made for some reason or not but I think leaving this linking to user preference will be more convenient because, as I think, the error handling for most user is done by `LSP` that can produce error message.

Linking `TSError` to `ErrorText` highlight the text without further information about why this highlight happens:
![out_000](https://user-images.githubusercontent.com/50509521/126864065-5a9307d8-0d25-474e-a1f0-bbadfa0a3d9e.png)

If the highlight linking exist for some reason, how can I clear the highlighting?
I used the following command in `init.lua` after loading `gruvbox-material` plugin without success:
```lua
vim.cmd('highlight! link TSError NONE')
```

**Comment by sainnhe** [comment]
Done via https://github.com/sainnhe/gruvbox-material/commit/7a1d276a3d938d488d2d592fbb52ecec642268fc.
