### ISSUE TITLE
When bg=light, matching MatchParen is of same colour

### ISSUE THREAD

**Issue by NilsIrl** [sainnhe/gruvbox-material#96]
- Operating system/version: MacOS
- Terminal emulator/version: iterm2
- `echo $TERM`: xterm-256color
- `vim --version` or `nvim --version`: NVIM v0.5.0

### Actual behaviour

<img width="322" alt="image" src="https://user-images.githubusercontent.com/26231126/127771732-e8026f97-e42b-4498-82aa-eb5828d28955.png">

For comparison here's what it looks like when bg=dark:

<img width="304" alt="image" src="https://user-images.githubusercontent.com/26231126/127771756-2525d6f9-ffc2-4527-ba08-8e3f8c46232e.png">

**Comment by sainnhe** [comment]
I don't really understand, do you mean the contrast of MatchParen should be higher?

Please describe the bug in detail.

**Comment by NilsIrl** [comment]
> I don't really understand, do you mean the contrast of MatchParen should be higher?

Yes

> Please describe the bug in detail.

If you look at the first screenshot (the light theme one), the cursor (on the opening brace) is of the same color as the matching paren indicator (on the closing brace)

**Comment by sainnhe** [comment]
Sorry for late reply, I just tried this on my machine but can't reproduce, the cursor displays correctly in the light variant (i.e. with black background and white foreground).

**Comment by NilsIrl** [comment]
I'm assuming you meant "with white background and black foreground".

Anyway if you can't reproduce, I'll just assume it's a problem with my setup.
