### ISSUE TITLE
Installing tree sitter parser for OCaml loses some highlighting.

### ISSUE THREAD

**Issue by theteachr** [sainnhe/gruvbox-material#97]
- Operating System: macOS Catalina
- Terminal Emulator: iTerm2, Kitty
- `echo $TERM`: `xterm-256color` `xterm-kitty`
- `nvim --version`:

```
NVIM v0.5.0-dev+1444-gc1120ad0e
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1624680915916.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Steps to reproduce
- Install tree sitter parser for OCaml

### Actual behaviour
![Screenshot 2021-08-08 at 10 06 56](https://user-images.githubusercontent.com/64728420/128757801-acd77495-bb7b-4476-86db-96342e777437.png)
After installing the parser, `None` and `Some` lose colors.

### Expected behaviour
![Screenshot 2021-08-08 at 10 05 52](https://user-images.githubusercontent.com/64728420/128757852-99be027a-4e92-4b5d-adfa-6ef303e8da25.png)
`None` and `Some` should have colors as above (when parser was not installed), along with additional coloring that comes when the parser is installed.

I have tested other colorschemes if they have the issue after the parser is installed, and they're working as expected. Turns out only the schemes by @sainnhe have this problem (Sonokai, Everforest, `this`).

The image below is using *tokyonight*, with the parser installed.
![Screenshot 2021-08-10 at 00 30 40](https://user-images.githubusercontent.com/64728420/128759834-5be775e6-8145-4cce-8268-abdf0475ad16.png)

**Comment by sainnhe** [comment]
Should be fixed now.
