### ISSUE TITLE
Hard to read line numbers

### ISSUE THREAD

**Issue by Gelio** [sainnhe/gruvbox-material#98]
Hey, thanks for creating and maintaining this color scheme!

I've noticed that after https://github.com/sainnhe/gruvbox-material/commit/37f8324bdc3033d3129092eb3016d89e02c1d4a2 the line numbers became much harder for me to read. I need them for relative jumps (with `set relativenumber`).

I am using the default configuration for this colorscheme (`mix` / `medium`):

![image](https://user-images.githubusercontent.com/889383/128820223-21df641c-f5d2-4f3f-b2a4-0a8d4e88abc0.png)

Here is how the line numbers look like as advertised in the screenshot in the README:

![image](https://user-images.githubusercontent.com/889383/128820385-5d2097b6-ba9c-4f04-80a2-8d8f7a6ec438.png)

I know I can override the colors (and I will do that shortly), but IMO since the contrast changed drastically, the default configuration for the colorscheme is no longer usable for me and possibly other users, hence I wanted to get that across and maybe changed

**Comment by sainnhe** [comment]
Although I prefer lower contrast design, but it's reasonable to provide a higher contrast variant.

I just added a new option via https://github.com/sainnhe/gruvbox-material/commit/2095e96daec72ed0c12870efc6577d58ff60195b which can be used to control the contrast of line numbers.

**Comment by Gelio** [comment]
Thanks! I appreciate the quick fix

**Comment by Foxtrod89** [comment]
> Although I prefer lower contrast design, but it's reasonable to provide a higher contrast variant.
> 
> I just added a new option via [2095e96](https://github.com/sainnhe/gruvbox-material/commit/2095e96daec72ed0c12870efc6577d58ff60195b) which can be used to control the contrast of line numbers.

Which key is responsible for line numbers!?

**Comment by Gelio** [comment]
I believe it is

```lua
vim.g.gruvbox_material_ui_contrast = "high"
```

https://github.com/Gelio/ubuntu-dotfiles/blob/ff611af6b5666bc65f123e86df2cfda23ee1dcfe/universal/neovim/config/nvim/lua/plugins/colorscheme.lua#L12

**Comment by Foxtrod89** [comment]
> I believe it is
> 
> ```lua
> vim.g.gruvbox_material_ui_contrast = "high"
> ```
> 
> https://github.com/Gelio/ubuntu-dotfiles/blob/ff611af6b5666bc65f123e86df2cfda23ee1dcfe/universal/neovim/config/nvim/lua/plugins/colorscheme.lua#L12

I mean to override with **g:gruvbox_material_colors_override**

**Comment by antoineco** [comment]
Colors override are for overriding _palette_ colors, so those changes apply to many highlight groups.

For changing the color of a specific highlight group, use an autocmd as explained in the docs: https://github.com/sainnhe/gruvbox-material/blob/7f56d9f9c4/doc/gruvbox-material.txt#L619
